// ----------------------------------------------------------------------
// LOS EMOJIS, CON NOMBRE.
//
// Antes eran una cadena de caracteres separados por espacios: se pintaban en
// una rejilla y ya. Para encontrar uno concreto habia que recorrerlos con la
// vista, categoria por categoria, y en "Objetos" hay setenta.
//
// Aqui cada uno lleva su nombre en español y, cuando hace falta, las palabras
// por las que la gente lo busca de verdad: nadie escribe "cara con lagrimas de
// alegria", escribe "risa". El nombre se enseña al pasar por encima y es lo que
// se busca al escribir.
//
// Cada entrada es [emoji, nombre, palabras] — `palabras` es opcional.
// ----------------------------------------------------------------------

export const CATEGORIAS_EMOJI = [
  {
    id: 'caras',
    nombre: 'Caras',
    icono: '😀',
    emojis: [
      ['😀', 'cara sonriente', 'feliz alegre sonrisa'],
      ['😃', 'cara sonriente con ojos grandes', 'feliz alegre'],
      ['😄', 'cara sonriente con ojos sonrientes', 'feliz alegre'],
      ['😁', 'cara radiante', 'feliz alegre dientes'],
      ['😆', 'cara sonriente con los ojos cerrados', 'risa carcajada'],
      ['😅', 'cara sonriente con sudor', 'alivio nervios risa'],
      ['😂', 'cara llorando de risa', 'risa carcajada jaja llorar'],
      ['🤣', 'revolcandose de risa', 'risa carcajada jaja'],
      ['😊', 'cara feliz con ojos sonrientes', 'timido contento'],
      ['😇', 'cara sonriente con aureola', 'angel santo bueno'],
      ['🙂', 'cara sonriendo un poco', 'sonrisa leve'],
      ['🙃', 'cara al reves', 'ironia sarcasmo'],
      ['😉', 'guiño', 'guiñar complice'],
      ['😌', 'cara aliviada', 'tranquilo paz'],
      ['😍', 'cara con ojos de corazon', 'amor enamorado'],
      ['🥰', 'cara sonriente con corazones', 'amor cariño'],
      ['😘', 'cara lanzando un beso', 'beso amor'],
      ['😗', 'cara besando', 'beso'],
      ['😙', 'cara besando con ojos sonrientes', 'beso'],
      ['😚', 'cara besando con los ojos cerrados', 'beso'],
      ['😋', 'cara saboreando', 'rico delicioso lengua'],
      ['😛', 'cara sacando la lengua', 'burla'],
      ['😝', 'cara sacando la lengua con ojos cerrados', 'burla'],
      ['😜', 'cara sacando la lengua y guiñando', 'burla travieso'],
      ['🤪', 'cara loca', 'loco chiflado'],
      ['🤨', 'cara con ceja levantada', 'duda sospecha'],
      ['🧐', 'cara con monoculo', 'analizar curioso'],
      ['🤓', 'cara de empollon', 'nerd gafas estudioso'],
      ['😎', 'cara con gafas de sol', 'genial cool'],
      ['🥸', 'cara disfrazada', 'disfraz bigote'],
      ['🤩', 'cara alucinando', 'estrellas asombro admiracion'],
      ['🥳', 'cara de fiesta', 'fiesta celebrar cumpleaños'],
      ['😏', 'cara de suficiencia', 'picaro presumido'],
      ['😒', 'cara de desaprobacion', 'fastidio hartazgo'],
      ['😞', 'cara decepcionada', 'triste desilusion'],
      ['😔', 'cara desanimada', 'triste pena'],
      ['😟', 'cara preocupada', 'preocupacion'],
      ['😕', 'cara de confusion', 'confundido'],
      ['🙁', 'cara con el ceño ligeramente fruncido', 'triste'],
      ['☹️', 'cara con el ceño fruncido', 'triste'],
      ['😣', 'cara de perseverancia', 'esfuerzo aguantar'],
      ['😖', 'cara de frustracion', 'frustrado'],
      ['😫', 'cara agotada', 'cansado harto'],
      ['😩', 'cara cansada', 'agotado harto'],
      ['🥺', 'cara suplicante', 'suplicar pena porfavor'],
      ['😢', 'cara llorando', 'triste llanto lagrima'],
      ['😭', 'cara llorando a mares', 'triste llanto'],
      ['😤', 'cara resoplando', 'enfado orgullo'],
      ['😠', 'cara enfadada', 'enojo molesto'],
      ['😡', 'cara muy enfadada', 'furia enojo rabia'],
      ['🤬', 'cara diciendo groserias', 'insulto enojo'],
      ['🤯', 'cabeza explotando', 'asombro sorpresa'],
      ['😳', 'cara sonrojada', 'verguenza sorpresa'],
      ['🥵', 'cara con calor', 'calor sofoco'],
      ['🥶', 'cara con frio', 'frio helado'],
      ['😱', 'cara gritando de miedo', 'susto miedo grito'],
      ['😨', 'cara asustada', 'miedo susto'],
      ['😰', 'cara angustiada con sudor', 'ansiedad nervios'],
      ['😥', 'cara triste pero aliviada', 'alivio pena'],
      ['😓', 'cara con sudor frio', 'cansancio nervios'],
      ['🫣', 'cara espiando', 'timidez mirar'],
      ['🤗', 'cara abrazando', 'abrazo cariño'],
      ['🤔', 'cara pensativa', 'pensar duda'],
      ['🫡', 'cara haciendo el saludo militar', 'saludo respeto'],
      ['🤭', 'cara con la mano en la boca', 'risa disimulo'],
      ['🫢', 'cara tapandose la boca', 'sorpresa asombro'],
      ['🫠', 'cara derritiendose', 'derretir calor verguenza'],
      ['🤥', 'cara de mentiroso', 'mentira pinocho'],
      ['😶', 'cara sin boca', 'silencio callado'],
      ['😐', 'cara neutral', 'indiferente'],
      ['😑', 'cara sin expresion', 'indiferente'],
      ['😬', 'cara haciendo una mueca', 'incomodo nervios'],
      ['🙄', 'cara con ojos en blanco', 'fastidio hartazgo'],
      ['😯', 'cara estupefacta', 'sorpresa'],
      ['😦', 'cara con el ceño fruncido y la boca abierta', 'sorpresa'],
      ['😧', 'cara angustiada', 'angustia'],
      ['😮', 'cara con la boca abierta', 'sorpresa asombro'],
      ['😲', 'cara atonita', 'asombro sorpresa'],
      ['🥱', 'cara bostezando', 'sueño aburrido'],
      ['😴', 'cara durmiendo', 'sueño dormir'],
      ['🤤', 'cara babeando', 'antojo baba'],
      ['😪', 'cara somnolienta', 'sueño cansancio'],
      ['😵', 'cara mareada', 'mareo aturdido'],
      ['🤐', 'cara con la boca cerrada con cremallera', 'silencio secreto'],
      ['🥴', 'cara atontada', 'mareo borracho'],
      ['🤢', 'cara con nauseas', 'asco vomito'],
      ['🤮', 'cara vomitando', 'asco vomito'],
      ['🤧', 'cara estornudando', 'resfriado gripe'],
      ['😷', 'cara con mascarilla', 'enfermo cubrebocas'],
      ['🤒', 'cara con termometro', 'fiebre enfermo'],
      ['🤕', 'cara con la cabeza vendada', 'herido golpe'],
    ],
  },
  {
    id: 'gestos',
    nombre: 'Gestos',
    icono: '👍',
    emojis: [
      ['👍', 'pulgar hacia arriba', 'bien ok aprobar like'],
      ['👎', 'pulgar hacia abajo', 'mal rechazar'],
      ['👊', 'puño cerrado', 'golpe choque'],
      ['✊', 'puño en alto', 'fuerza lucha'],
      ['🤛', 'puño hacia la izquierda', 'choque'],
      ['🤜', 'puño hacia la derecha', 'choque'],
      ['👏', 'aplausos', 'aplaudir felicidades bravo'],
      ['🙌', 'manos levantadas', 'celebrar alabanza gloria'],
      ['👐', 'manos abiertas', 'abrir recibir'],
      ['🤲', 'palmas hacia arriba', 'pedir orar'],
      ['🤝', 'apreton de manos', 'acuerdo trato saludo'],
      ['🙏', 'manos en oracion', 'orar rezar gracias porfavor'],
      ['✍️', 'mano escribiendo', 'escribir firmar'],
      ['💪', 'biceps', 'fuerza fuerte musculo'],
      ['🦾', 'brazo mecanico', 'protesis fuerza'],
      ['🖐️', 'mano abierta con dedos separados', 'saludo parar'],
      ['✋', 'mano levantada', 'alto parar saludo'],
      ['🤚', 'dorso de la mano', 'mano'],
      ['👋', 'mano saludando', 'hola adios saludo'],
      ['🤙', 'llamame', 'llamar telefono'],
      ['🤌', 'dedos juntos', 'gesto italiano'],
      ['🤏', 'pellizco', 'poquito pequeño'],
      ['✌️', 'señal de victoria', 'paz victoria dos'],
      ['🤞', 'dedos cruzados', 'suerte deseo'],
      ['🫰', 'dedos haciendo corazon', 'corazon amor'],
      ['🤟', 'te quiero', 'amor'],
      ['🤘', 'cuernos', 'rock'],
      ['👌', 'de acuerdo', 'ok perfecto bien'],
      ['👈', 'dedo apuntando a la izquierda', 'señalar'],
      ['👉', 'dedo apuntando a la derecha', 'señalar'],
      ['👆', 'dedo apuntando hacia arriba', 'señalar'],
      ['👇', 'dedo apuntando hacia abajo', 'señalar'],
      ['☝️', 'dedo indice hacia arriba', 'atencion uno'],
      ['🫵', 'dedo apuntandote', 'tu señalar'],
    ],
  },
  {
    id: 'personas',
    nombre: 'Personas',
    icono: '🧑',
    emojis: [
      ['👶', 'bebe', 'niño recien nacido'],
      ['🧒', 'criatura', 'niño niña'],
      ['👦', 'niño', 'chico'],
      ['👧', 'niña', 'chica'],
      ['🧑', 'persona', 'adulto'],
      ['👨', 'hombre', 'señor'],
      ['👩', 'mujer', 'señora'],
      ['🧔', 'persona con barba', 'barba'],
      ['👱', 'persona rubia', 'rubio'],
      ['👴', 'hombre mayor', 'abuelo anciano'],
      ['👵', 'mujer mayor', 'abuela anciana'],
      ['🙍', 'persona con el ceño fruncido', 'enfado'],
      ['🙎', 'persona haciendo pucheros', 'puchero'],
      ['🙅', 'persona haciendo el gesto de no', 'no negar'],
      ['🙆', 'persona haciendo el gesto de si', 'si aprobar'],
      ['💁', 'persona dando informacion', 'informacion ayuda'],
      ['🙋', 'persona levantando la mano', 'pregunta presente'],
      ['🧏', 'persona sorda', 'sordo'],
      ['🙇', 'persona haciendo una reverencia', 'reverencia disculpa'],
      ['🤦', 'persona con la mano en la cara', 'verguenza ajena'],
      ['🤷', 'persona encogiendose de hombros', 'no se duda'],
      ['👮', 'policia', 'agente'],
      ['👷', 'obrero', 'construccion casco'],
      ['💂', 'guardia', 'soldado'],
      ['🕵️', 'detective', 'investigar espia'],
      ['👩‍⚕️', 'doctora', 'medica enfermera salud'],
      ['👨‍⚕️', 'doctor', 'medico enfermero salud'],
      ['👩‍🏫', 'maestra', 'profesora enseñar'],
      ['👨‍🏫', 'maestro', 'profesor enseñar'],
      ['👩‍🍳', 'cocinera', 'chef'],
      ['👨‍🍳', 'cocinero', 'chef'],
      ['👩‍💻', 'informatica', 'programadora computadora'],
      ['👨‍💻', 'informatico', 'programador computadora'],
      ['👩‍🎤', 'cantante', 'musica'],
      ['👨‍🎤', 'cantante', 'musica'],
      ['👩‍🚀', 'astronauta', 'espacio'],
      ['👨‍🚀', 'astronauta', 'espacio'],
      ['🧙', 'mago', 'magia hechicero'],
      ['🧚', 'hada', 'magia'],
      ['🧛', 'vampiro', 'dracula'],
      ['🧜', 'sirena', 'mar'],
      ['🧝', 'elfo', 'fantasia'],
      ['🧞', 'genio', 'lampara deseo'],
      ['🧟', 'zombi', 'muerto'],
    ],
  },
  {
    id: 'corazones',
    nombre: 'Corazones',
    icono: '❤️',
    emojis: [
      ['❤️', 'corazon rojo', 'amor te quiero'],
      ['🧡', 'corazon naranja', 'amor'],
      ['💛', 'corazon amarillo', 'amor amistad'],
      ['💚', 'corazon verde', 'amor'],
      ['💙', 'corazon azul', 'amor'],
      ['💜', 'corazon morado', 'amor'],
      ['🖤', 'corazon negro', 'luto'],
      ['🤍', 'corazon blanco', 'pureza'],
      ['🤎', 'corazon marron', 'amor'],
      ['💔', 'corazon roto', 'tristeza desamor'],
      ['❤️‍🔥', 'corazon en llamas', 'pasion amor'],
      ['❤️‍🩹', 'corazon curandose', 'sanar recuperacion'],
      ['❣️', 'corazon de exclamacion', 'amor'],
      ['💕', 'dos corazones', 'amor cariño'],
      ['💞', 'corazones giratorios', 'amor'],
      ['💓', 'corazon latiendo', 'amor latido'],
      ['💗', 'corazon creciendo', 'amor'],
      ['💖', 'corazon brillante', 'amor'],
      ['💘', 'corazon con flecha', 'enamorado cupido'],
      ['💝', 'corazon con lazo', 'regalo amor'],
      ['💟', 'decoracion de corazon', 'amor'],
      ['💌', 'carta de amor', 'carta amor'],
      ['💋', 'marca de beso', 'beso labios'],
      ['💯', 'cien puntos', 'perfecto total'],
      ['💢', 'simbolo de enfado', 'enojo'],
      ['💥', 'explosion', 'choque boom'],
      ['💫', 'mareo', 'estrellas'],
      ['💦', 'gotas de sudor', 'agua sudor'],
      ['💨', 'ráfaga de aire', 'viento rapido'],
      ['🕳️', 'agujero', 'hoyo'],
    ],
  },
  {
    id: 'animales',
    nombre: 'Animales',
    icono: '🐶',
    emojis: [
      ['🐶', 'perro', 'perrito cachorro'],
      ['🐱', 'gato', 'gatito'],
      ['🐭', 'raton', 'ratoncito'],
      ['🐹', 'hamster', 'roedor'],
      ['🐰', 'conejo', 'conejito'],
      ['🦊', 'zorro', ''],
      ['🐻', 'oso', ''],
      ['🐼', 'panda', 'oso'],
      ['🐻‍❄️', 'oso polar', 'oso blanco'],
      ['🐨', 'koala', ''],
      ['🐯', 'tigre', ''],
      ['🦁', 'leon', ''],
      ['🐮', 'vaca', ''],
      ['🐷', 'cerdo', 'puerco cochino'],
      ['🐽', 'nariz de cerdo', 'hocico'],
      ['🐸', 'rana', 'sapo'],
      ['🐵', 'mono', 'chango'],
      ['🙈', 'mono que no ve', 'no veo verguenza'],
      ['🙉', 'mono que no oye', 'no oigo'],
      ['🙊', 'mono que no habla', 'no digo secreto'],
      ['🐒', 'mono', 'chango'],
      ['🐔', 'gallina', 'pollo'],
      ['🐧', 'pinguino', ''],
      ['🐦', 'pajaro', 'ave'],
      ['🐤', 'pollito', 'pollo'],
      ['🐣', 'pollito saliendo del cascaron', 'nacer'],
      ['🦆', 'pato', ''],
      ['🦅', 'aguila', 'ave'],
      ['🦉', 'buho', 'lechuza'],
      ['🦇', 'murcielago', ''],
      ['🐺', 'lobo', ''],
      ['🐗', 'jabali', 'cerdo salvaje'],
      ['🐴', 'caballo', ''],
      ['🦄', 'unicornio', 'magia'],
      ['🐝', 'abeja', 'miel'],
      ['🪱', 'lombriz', 'gusano'],
      ['🐛', 'oruga', 'gusano'],
      ['🦋', 'mariposa', ''],
      ['🐌', 'caracol', 'lento'],
      ['🐞', 'mariquita', 'catarina'],
      ['🐜', 'hormiga', ''],
      ['🦟', 'mosquito', 'zancudo'],
      ['🦗', 'grillo', ''],
      ['🕷️', 'araña', ''],
      ['🦂', 'escorpion', 'alacran'],
      ['🐢', 'tortuga', 'lento'],
      ['🐍', 'serpiente', 'culebra'],
      ['🦎', 'lagarto', 'lagartija'],
      ['🐙', 'pulpo', ''],
      ['🦑', 'calamar', ''],
      ['🦐', 'camaron', 'gamba'],
      ['🦞', 'langosta', ''],
      ['🦀', 'cangrejo', ''],
      ['🐡', 'pez globo', ''],
      ['🐠', 'pez tropical', ''],
      ['🐟', 'pez', 'pescado'],
      ['🐬', 'delfin', ''],
      ['🐳', 'ballena', ''],
      ['🐋', 'ballena', ''],
      ['🦈', 'tiburon', ''],
    ],
  },
  {
    id: 'comida',
    nombre: 'Comida',
    icono: '🍎',
    emojis: [
      ['🍏', 'manzana verde', 'fruta'],
      ['🍎', 'manzana', 'fruta roja'],
      ['🍐', 'pera', 'fruta'],
      ['🍊', 'naranja', 'mandarina fruta'],
      ['🍋', 'limon', 'fruta acido'],
      ['🍌', 'guineo', 'platano banana fruta'],
      ['🍉', 'sandia', 'patilla fruta'],
      ['🍇', 'uvas', 'fruta'],
      ['🍓', 'fresa', 'fruta'],
      ['🫐', 'arandanos', 'fruta'],
      ['🍈', 'melon', 'fruta'],
      ['🍒', 'cerezas', 'fruta'],
      ['🍑', 'melocoton', 'durazno fruta'],
      ['🥭', 'mango', 'fruta'],
      ['🍍', 'piña', 'fruta'],
      ['🥥', 'coco', 'fruta'],
      ['🥝', 'kiwi', 'fruta'],
      ['🍅', 'tomate', 'verdura'],
      ['🥑', 'aguacate', 'palta'],
      ['🍆', 'berenjena', 'verdura'],
      ['🥔', 'papa', 'patata'],
      ['🥕', 'zanahoria', 'verdura'],
      ['🌽', 'maiz', 'mazorca elote'],
      ['🌶️', 'chile picante', 'aji picante'],
      ['🫑', 'pimiento', 'aji morron'],
      ['🥒', 'pepino', 'verdura'],
      ['🥬', 'lechuga', 'verdura hoja'],
      ['🥦', 'brocoli', 'verdura'],
      ['🧄', 'ajo', ''],
      ['🧅', 'cebolla', ''],
      ['🍄', 'seta', 'hongo champiñon'],
      ['🥜', 'cacahuate', 'mani'],
      ['🫘', 'frijoles', 'habichuelas'],
      ['🌰', 'castaña', 'nuez'],
      ['🍞', 'pan', ''],
      ['🥐', 'croissant', 'cuernito'],
      ['🥖', 'baguette', 'pan'],
      ['🫓', 'pan plano', 'tortilla'],
      ['🥨', 'pretzel', ''],
      ['🥯', 'rosquilla de pan', 'bagel'],
      ['🥞', 'panqueques', 'hotcakes tortitas'],
      ['🧇', 'gofre', 'waffle'],
      ['🧀', 'queso', ''],
      ['🍖', 'carne con hueso', 'carne'],
      ['🍗', 'muslo de pollo', 'pollo carne'],
      ['🥩', 'corte de carne', 'bistec carne'],
      ['🥓', 'tocino', 'bacon'],
      ['🍔', 'hamburguesa', ''],
      ['🍟', 'papas fritas', 'patatas'],
      ['🍕', 'pizza', ''],
      ['🌭', 'hot dog', 'perro caliente'],
      ['🥪', 'sandwich', 'emparedado'],
      ['🌮', 'taco', ''],
      ['🌯', 'burrito', ''],
      ['🫔', 'tamal', ''],
      ['🥙', 'pan relleno', 'kebab'],
      ['🧆', 'falafel', ''],
      ['🥚', 'huevo', ''],
      ['🍳', 'huevo frito', 'cocinar sarten'],
      ['🥘', 'paella', 'guiso sarten'],
      ['🍲', 'olla de comida', 'sopa guiso sancocho'],
      ['🫕', 'fondue', ''],
      ['🥣', 'tazon con cuchara', 'cereal sopa'],
      ['🥗', 'ensalada', 'verde'],
      ['🍿', 'palomitas', 'cine maiz'],
      ['🧈', 'mantequilla', ''],
      ['🧂', 'sal', 'salero'],
    ],
  },
  {
    id: 'actividad',
    nombre: 'Actividad',
    icono: '⚽',
    emojis: [
      ['⚽', 'balon de futbol', 'futbol deporte pelota'],
      ['🏀', 'baloncesto', 'basquet pelota deporte'],
      ['🏈', 'futbol americano', 'deporte'],
      ['⚾', 'beisbol', 'pelota deporte'],
      ['🥎', 'softbol', 'pelota deporte'],
      ['🎾', 'tenis', 'pelota deporte'],
      ['🏐', 'voleibol', 'pelota deporte'],
      ['🏉', 'rugby', 'deporte'],
      ['🥏', 'disco volador', 'frisbee'],
      ['🎱', 'bola ocho', 'billar pool'],
      ['🪀', 'yoyo', 'juguete'],
      ['🏓', 'ping pong', 'tenis de mesa'],
      ['🏸', 'badminton', 'deporte'],
      ['🏒', 'hockey sobre hielo', 'deporte'],
      ['🏑', 'hockey sobre hierba', 'deporte'],
      ['🥍', 'lacrosse', 'deporte'],
      ['🏏', 'criquet', 'deporte'],
      ['🥅', 'porteria', 'gol arco'],
      ['⛳', 'bandera de golf', 'golf hoyo'],
      ['🪁', 'cometa', 'papalote chichigua'],
      ['🏹', 'arco y flecha', 'tiro arqueria'],
      ['🎣', 'caña de pescar', 'pescar'],
      ['🤿', 'buceo', 'mascara submarinismo'],
      ['🥊', 'guante de boxeo', 'boxeo pelea'],
      ['🥋', 'traje de artes marciales', 'karate judo'],
      ['🎽', 'camiseta de correr', 'atletismo'],
      ['🛹', 'patineta', 'skate'],
      ['🛼', 'patines', 'patinar'],
      ['🛷', 'trineo', 'nieve'],
      ['⛸️', 'patin de hielo', 'patinar'],
      ['🥌', 'curling', 'deporte hielo'],
      ['🎿', 'esquis', 'esquiar nieve'],
      ['⛷️', 'esquiador', 'esquiar nieve'],
      ['🏂', 'tabla de snowboard', 'nieve'],
      ['🪂', 'paracaidas', 'saltar'],
      ['🏋️', 'levantamiento de pesas', 'gimnasio pesas'],
      ['🤼', 'lucha libre', 'pelea deporte'],
      ['🤸', 'voltereta', 'gimnasia'],
      ['⛹️', 'persona botando el balon', 'baloncesto'],
      ['🤺', 'esgrima', 'espada'],
      ['🤾', 'balonmano', 'deporte'],
      ['🏌️', 'golfista', 'golf'],
      ['🏇', 'carrera de caballos', 'jinete'],
      ['🧘', 'persona en posicion de loto', 'yoga meditar'],
      ['🏄', 'surfista', 'surf ola'],
      ['🏊', 'nadador', 'nadar piscina'],
      ['🤽', 'waterpolo', 'nadar'],
      ['🚣', 'persona remando', 'bote remo'],
      ['🧗', 'escalador', 'escalar montaña'],
      ['🚴', 'ciclista', 'bicicleta'],
      ['🚵', 'ciclista de montaña', 'bicicleta'],
      ['🎮', 'mando de videojuegos', 'videojuego jugar'],
      ['🕹️', 'palanca de mando', 'joystick videojuego'],
      ['🎲', 'dado', 'juego azar'],
      ['♟️', 'peon de ajedrez', 'ajedrez'],
      ['🎯', 'diana', 'objetivo blanco meta'],
      ['🎳', 'bolos', 'boliche'],
    ],
  },
  {
    id: 'viajes',
    nombre: 'Viajes',
    icono: '✈️',
    emojis: [
      ['🚗', 'carro', 'coche auto'],
      ['🚕', 'taxi', ''],
      ['🚙', 'todoterreno', 'jeep camioneta'],
      ['🚌', 'autobus', 'guagua camion'],
      ['🚎', 'trolebus', 'autobus'],
      ['🏎️', 'carro de carreras', 'formula uno'],
      ['🚓', 'patrulla', 'policia'],
      ['🚑', 'ambulancia', 'emergencia'],
      ['🚒', 'camion de bomberos', 'bomberos'],
      ['🚐', 'minibus', 'furgoneta van'],
      ['🛻', 'camioneta', 'pickup'],
      ['🚚', 'camion de reparto', 'camion'],
      ['🚛', 'camion articulado', 'trailer'],
      ['🚜', 'tractor', 'campo'],
      ['🏍️', 'motocicleta', 'moto'],
      ['🛵', 'motoneta', 'scooter moto'],
      ['🚲', 'bicicleta', 'bici'],
      ['🛴', 'patinete', 'scooter'],
      ['🛹', 'patineta', 'skate'],
      ['🛼', 'patines', 'patinar'],
      ['🚨', 'sirena', 'emergencia alarma'],
      ['🚔', 'patrulla de frente', 'policia'],
      ['🚍', 'autobus de frente', 'guagua'],
      ['🚘', 'carro de frente', 'coche auto'],
      ['🚖', 'taxi de frente', 'taxi'],
      ['🚡', 'telecabina', 'teleferico'],
      ['🚠', 'teleferico', 'montaña'],
      ['🚟', 'tren suspendido', 'tren'],
      ['🚃', 'vagon', 'tren'],
      ['🚋', 'vagon de tranvia', 'tranvia'],
      ['🚞', 'tren de montaña', 'tren'],
      ['🚝', 'monorriel', 'tren'],
      ['🚄', 'tren de alta velocidad', 'tren bala'],
      ['🚅', 'tren bala', 'tren rapido'],
      ['🚈', 'tren ligero', 'tren'],
      ['🚂', 'locomotora', 'tren vapor'],
      ['🚆', 'tren', ''],
      ['🚇', 'metro', 'subterraneo'],
      ['🚊', 'tranvia', ''],
      ['🚉', 'estacion de tren', 'tren'],
      ['✈️', 'avion', 'volar viaje'],
      ['🛫', 'avion despegando', 'salida vuelo'],
      ['🛬', 'avion aterrizando', 'llegada vuelo'],
      ['🛩️', 'avioneta', 'avion pequeño'],
      ['💺', 'asiento', 'avion silla'],
      ['🚁', 'helicoptero', ''],
      ['🚀', 'cohete', 'espacio lanzar'],
      ['🛸', 'platillo volador', 'ovni'],
      ['⛵', 'velero', 'barco vela'],
      ['🚤', 'lancha', 'bote rapido'],
      ['🛥️', 'yate', 'barco'],
      ['🛳️', 'crucero', 'barco'],
      ['⛴️', 'transbordador', 'ferry barco'],
      ['🚢', 'barco', 'buque'],
      ['⚓', 'ancla', 'barco mar'],
      ['🛟', 'salvavidas', 'flotador rescate'],
      ['🗽', 'estatua de la libertad', 'nueva york'],
      ['🗼', 'torre de tokio', 'torre'],
      ['🏰', 'castillo', ''],
      ['🏯', 'castillo japones', ''],
      ['🏟️', 'estadio', 'deporte'],
      ['🎡', 'rueda de la fortuna', 'feria'],
      ['🎢', 'montaña rusa', 'feria'],
      ['🎠', 'carrusel', 'feria caballitos'],
      ['⛲', 'fuente', 'agua'],
      ['⛱️', 'sombrilla de playa', 'playa sol'],
      ['🏖️', 'playa', 'arena mar'],
      ['🏝️', 'isla desierta', 'isla playa'],
      ['🏜️', 'desierto', 'arena cactus'],
      ['🌋', 'volcan', 'erupcion'],
      ['⛰️', 'montaña', 'cerro'],
      ['🏔️', 'montaña nevada', 'nieve cerro'],
    ],
  },
  {
    id: 'objetos',
    nombre: 'Objetos',
    icono: '💡',
    emojis: [
      ['⌚', 'reloj de pulsera', 'hora'],
      ['📱', 'celular', 'movil telefono'],
      ['📲', 'celular con flecha', 'llamada movil'],
      ['💻', 'computadora portatil', 'laptop ordenador'],
      ['⌨️', 'teclado', 'escribir'],
      ['🖥️', 'computadora de escritorio', 'monitor ordenador'],
      ['🖨️', 'impresora', 'imprimir'],
      ['🖱️', 'raton de computadora', 'mouse'],
      ['🖲️', 'bola de seguimiento', 'trackball'],
      ['🕹️', 'palanca de mando', 'joystick'],
      ['🗜️', 'prensa', 'comprimir'],
      ['💽', 'minidisco', 'disco'],
      ['💾', 'disquete', 'guardar disco'],
      ['💿', 'disco compacto', 'cd'],
      ['📀', 'dvd', 'disco'],
      ['📼', 'cinta de video', 'vhs'],
      ['📷', 'camara', 'foto'],
      ['📸', 'camara con flash', 'foto'],
      ['📹', 'camara de video', 'grabar video'],
      ['🎥', 'camara de cine', 'pelicula'],
      ['📽️', 'proyector', 'cine'],
      ['🎞️', 'rollo de pelicula', 'cine'],
      ['📞', 'telefono', 'llamar'],
      ['☎️', 'telefono fijo', 'llamar'],
      ['📟', 'buscapersonas', 'beeper'],
      ['📠', 'fax', ''],
      ['📺', 'television', 'tele'],
      ['📻', 'radio', ''],
      ['🎙️', 'microfono de estudio', 'grabar podcast'],
      ['🎚️', 'control deslizante', 'volumen'],
      ['🎛️', 'controles de sonido', 'perillas'],
      ['🧭', 'brujula', 'norte orientacion'],
      ['⏱️', 'cronometro', 'tiempo'],
      ['⏲️', 'temporizador', 'tiempo'],
      ['⏰', 'despertador', 'alarma reloj'],
      ['🕰️', 'reloj de chimenea', 'reloj'],
      ['⌛', 'reloj de arena', 'tiempo espera'],
      ['⏳', 'reloj de arena con arena cayendo', 'tiempo espera'],
      ['📡', 'antena satelital', 'señal'],
      ['🔋', 'bateria', 'pila carga'],
      ['🪫', 'bateria baja', 'pila descargada'],
      ['🔌', 'enchufe', 'corriente electricidad'],
      ['💡', 'bombilla', 'idea luz foco'],
      ['🔦', 'linterna', 'luz'],
      ['🕯️', 'vela', 'luz'],
      ['🪔', 'lampara de aceite', 'luz'],
      ['🧯', 'extintor', 'fuego'],
      ['🛢️', 'barril de petroleo', 'aceite'],
      ['💸', 'dinero con alas', 'gasto plata'],
      ['💵', 'billete de dolar', 'dinero plata'],
      ['💴', 'billete de yen', 'dinero'],
      ['💶', 'billete de euro', 'dinero'],
      ['💷', 'billete de libra', 'dinero'],
      ['🪙', 'moneda', 'dinero'],
      ['💰', 'bolsa de dinero', 'dinero plata'],
      ['💳', 'tarjeta de credito', 'pago banco'],
      ['💎', 'diamante', 'joya'],
      ['⚖️', 'balanza', 'justicia peso'],
      ['🪜', 'escalera', 'subir'],
      ['🧰', 'caja de herramientas', 'herramientas'],
      ['🪛', 'destornillador', 'herramienta'],
      ['🔧', 'llave inglesa', 'herramienta arreglar'],
      ['🔨', 'martillo', 'herramienta'],
      ['⚒️', 'martillo y pico', 'herramientas'],
      ['🛠️', 'martillo y llave', 'herramientas arreglar'],
      ['⛏️', 'pico', 'herramienta minar'],
      ['🪚', 'serrucho', 'sierra herramienta'],
      ['🔩', 'tornillo y tuerca', 'herramienta'],
      ['⚙️', 'engranaje', 'ajustes configuracion'],
      ['🧱', 'ladrillo', 'construccion pared'],
    ],
  },
  {
    id: 'simbolos',
    nombre: 'Símbolos',
    icono: '✅',
    emojis: [
      ['✅', 'marca de verificacion verde', 'listo hecho correcto si'],
      ['☑️', 'casilla marcada', 'listo hecho'],
      ['✔️', 'marca de verificacion', 'correcto listo'],
      ['❌', 'cruz roja', 'no error mal cancelar'],
      ['❎', 'cruz en un cuadro', 'no error'],
      ['➕', 'signo de mas', 'sumar añadir'],
      ['➖', 'signo de menos', 'restar quitar'],
      ['➗', 'signo de division', 'dividir'],
      ['✖️', 'signo de multiplicacion', 'multiplicar por'],
      ['💲', 'simbolo de dolar', 'dinero precio'],
      ['💱', 'cambio de divisas', 'moneda cambio'],
      ['™️', 'marca comercial', 'trademark'],
      ['©️', 'derechos de autor', 'copyright'],
      ['®️', 'marca registrada', 'registrado'],
      ['〰️', 'linea ondulada', 'onda'],
      ['➰', 'bucle', 'rizo'],
      ['➿', 'doble bucle', 'rizo'],
      ['🔚', 'fin', 'final'],
      ['🔙', 'atras', 'volver'],
      ['🔛', 'encendido', 'activo'],
      ['🔝', 'arriba', 'top'],
      ['🔜', 'pronto', 'proximamente'],
      ['❕', 'exclamacion blanca', 'atencion'],
      ['❔', 'interrogacion blanca', 'duda pregunta'],
      ['❗', 'signo de exclamacion', 'atencion importante'],
      ['❓', 'signo de interrogacion', 'pregunta duda'],
      ['‼️', 'doble exclamacion', 'atencion'],
      ['⁉️', 'exclamacion e interrogacion', 'sorpresa duda'],
      ['💬', 'globo de dialogo', 'mensaje hablar chat'],
      ['💭', 'globo de pensamiento', 'pensar'],
      ['🗯️', 'globo de enfado', 'gritar enojo'],
      ['♠️', 'picas', 'cartas baraja'],
      ['♥️', 'corazones', 'cartas baraja'],
      ['♦️', 'diamantes', 'cartas baraja'],
      ['♣️', 'treboles', 'cartas baraja'],
      ['🃏', 'comodin', 'cartas joker'],
      ['🀄', 'mahjong', 'juego'],
      ['🎴', 'cartas de flores', 'juego'],
      ['🔇', 'silencio', 'mudo sin sonido'],
      ['🔈', 'altavoz bajo', 'volumen sonido'],
      ['🔉', 'altavoz medio', 'volumen sonido'],
      ['🔊', 'altavoz alto', 'volumen sonido'],
      ['📢', 'altavoz', 'anuncio megafono'],
      ['📣', 'megafono', 'anuncio gritar'],
      ['🔔', 'campana', 'notificacion aviso'],
      ['🔕', 'campana tachada', 'silenciar sin aviso'],
      ['🎵', 'nota musical', 'musica'],
      ['🎶', 'notas musicales', 'musica cancion'],
      ['💹', 'grafico con tendencia al alza', 'bolsa subida'],
      ['🛐', 'lugar de culto', 'religion oracion'],
      ['⚛️', 'simbolo atomico', 'ciencia atomo'],
      ['🕉️', 'om', 'hinduismo'],
      ['✡️', 'estrella de david', 'judaismo'],
      ['☸️', 'rueda del dharma', 'budismo'],
      ['☯️', 'yin yang', 'equilibrio'],
      ['✝️', 'cruz latina', 'cristiano iglesia fe'],
      ['☦️', 'cruz ortodoxa', 'cristiano'],
      ['☪️', 'estrella y luna creciente', 'islam'],
      ['☮️', 'simbolo de la paz', 'paz'],
      ['🕎', 'candelabro', 'menora'],
      ['🔯', 'estrella de seis puntas', 'estrella'],
      ['♈', 'aries', 'zodiaco signo'],
      ['♉', 'tauro', 'zodiaco signo'],
      ['♊', 'geminis', 'zodiaco signo'],
      ['♋', 'cancer', 'zodiaco signo'],
      ['♌', 'leo', 'zodiaco signo'],
      ['♍', 'virgo', 'zodiaco signo'],
      ['♎', 'libra', 'zodiaco signo'],
      ['♏', 'escorpio', 'zodiaco signo'],
      ['♐', 'sagitario', 'zodiaco signo'],
      ['♑', 'capricornio', 'zodiaco signo'],
      ['♒', 'acuario', 'zodiaco signo'],
      ['♓', 'piscis', 'zodiaco signo'],
    ],
  },
  {
    id: 'banderas',
    nombre: 'Banderas',
    icono: '🇩🇴',
    emojis: [
      ['🇩🇴', 'republica dominicana', 'quisqueya rd bandera'],
      ['🇺🇸', 'estados unidos', 'usa eeuu bandera'],
      ['🇵🇷', 'puerto rico', 'bandera'],
      ['🇪🇸', 'españa', 'bandera'],
      ['🇲🇽', 'mexico', 'bandera'],
      ['🇨🇴', 'colombia', 'bandera'],
      ['🇻🇪', 'venezuela', 'bandera'],
      ['🇨🇺', 'cuba', 'bandera'],
      ['🇭🇹', 'haiti', 'bandera'],
      ['🇵🇦', 'panama', 'bandera'],
      ['🇨🇷', 'costa rica', 'bandera'],
      ['🇭🇳', 'honduras', 'bandera'],
      ['🇳🇮', 'nicaragua', 'bandera'],
      ['🇸🇻', 'el salvador', 'bandera'],
      ['🇬🇹', 'guatemala', 'bandera'],
      ['🇧🇷', 'brasil', 'bandera'],
      ['🇦🇷', 'argentina', 'bandera'],
      ['🇨🇱', 'chile', 'bandera'],
      ['🇵🇪', 'peru', 'bandera'],
      ['🇪🇨', 'ecuador', 'bandera'],
      ['🇺🇾', 'uruguay', 'bandera'],
      ['🇵🇾', 'paraguay', 'bandera'],
      ['🇧🇴', 'bolivia', 'bandera'],
      ['🇨🇦', 'canada', 'bandera'],
      ['🇬🇧', 'reino unido', 'inglaterra bandera'],
      ['🇫🇷', 'francia', 'bandera'],
      ['🇩🇪', 'alemania', 'bandera'],
      ['🇮🇹', 'italia', 'bandera'],
      ['🇵🇹', 'portugal', 'bandera'],
      ['🇯🇵', 'japon', 'bandera'],
      ['🇨🇳', 'china', 'bandera'],
      ['🇰🇷', 'corea del sur', 'bandera'],
      ['🇮🇳', 'india', 'bandera'],
      ['🇦🇺', 'australia', 'bandera'],
    ],
  },
];

// ----------------------------------------------------------------------

/**
 * Sin tildes y en minusculas.
 *
 * Quien busca "corazon" tiene que encontrar "corazón", y quien busca "PIÑA"
 * tiene que encontrar "piña". La eñe se respeta —es otra letra, no una ene con
 * adorno—, pero se comparan igual las dos formas por si acaso.
 */
const normalizar = (texto) =>
  String(texto ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-̂̄-ͯ]/g, '')
    .trim();

/** Todos, en una sola lista, con el texto por el que se buscan ya preparado. */
export const TODOS_LOS_EMOJIS = CATEGORIAS_EMOJI.flatMap((categoria) =>
  categoria.emojis.map(([emoji, nombre, palabras = '']) => ({
    emoji,
    nombre,
    categoria: categoria.id,
    busqueda: normalizar(`${nombre} ${palabras}`),
  }))
);

const POR_EMOJI = new Map(TODOS_LOS_EMOJIS.map((entrada) => [entrada.emoji, entrada]));

/** El nombre de un emoji, o el propio emoji si no esta en la lista. */
export const nombreDelEmoji = (emoji) => POR_EMOJI.get(emoji)?.nombre ?? emoji;

/**
 * Los que coinciden con lo que se escribio.
 *
 * Se parte en palabras y se exigen TODAS: "cara triste" no puede devolver todas
 * las caras y todo lo triste, sino lo que es las dos cosas. Primero los que
 * empiezan por lo escrito, que es casi siempre lo que se quiere.
 */
export const buscarEmojis = (texto) => {
  const consulta = normalizar(texto);

  if (!consulta) return [];

  const palabras = consulta.split(/\s+/).filter(Boolean);
  const coinciden = TODOS_LOS_EMOJIS.filter((entrada) =>
    palabras.every((palabra) => entrada.busqueda.includes(palabra))
  );

  return coinciden.sort((a, b) => {
    const empiezaA = a.busqueda.startsWith(consulta) ? 0 : 1;
    const empiezaB = b.busqueda.startsWith(consulta) ? 0 : 1;

    return empiezaA - empiezaB;
  });
};
