// ----------------------------------------------------------------------
// EL CATALOGO DEL SISTEMA DE ASCENSO, TAL COMO ESTA EN LA CARPETA OFICIAL.
//
// Transcripcion del inventario "Exploradores, Seguidores y Pioneros" (490
// archivos, 28/08/2026): cada division con sus carpetas y, dentro, los premios
// que contiene. De aqui salen tres cosas a la vez, y por eso vive en un solo
// sitio:
//
//   - El arbol que se navega en la ficha del miembro (Sistema de Ascenso).
//   - Las rutas que ofrece el selector de los certificados automaticos.
//   - Los documentos que se registran en Firebase.
//
// PARA ANADIR UN PREMIO basta con escribirlo en su lista. El id se calcula solo
// a partir de la RUTA -division, carpetas y nombre-, nunca del nombre suelto:
// hay premios que se llaman igual en varias divisiones ("Lectura de la Biblia"
// esta en las tres) y un id por nombre los confundiria entre si.
//
// Dos cosas del inventario que aqui NO estan, a proposito:
//
//   - Los "(1)" de los nombres: son copias del mismo archivo, asi que Fotografia
//     y 1 SAMUEL aparecen una sola vez.
//   - Los dos "Orden.png" de los premios biblicos: son una hoja con el orden de
//     lectura, no un premio que nadie complete.
// ----------------------------------------------------------------------

export const ID_RAIZ_SISTEMA_ASCENSO = 'sistema-de-ascenso';

// El id sale de la ruta entera, con doble guion bajo entre tramos para que no se
// confunda con los guiones que ya llevan los nombres ("Destreza - Plata").
export const idDeRutaAscenso = (...tramos) =>
  tramos
    .map((tramo) =>
      String(tramo)
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
    )
    .join('__');

// La sigla es la que el catalogo ya usaba para cada division.
export const DIVISIONES_ASCENSO = [
  { nombre: 'Exploradores', sigla: 'EX' },
  { nombre: 'Seguidores', sigla: 'SS' },
  { nombre: 'Pioneros', sigla: 'PI' },
];

// Los premios que cuelgan de la division misma, sin carpeta de por medio.
export const PREMIOS_EN_RAIZ_ASCENSO = {
  'Exploradores': [
    'Manual del Muchacho - Exploradores',
  ],
  'Seguidores': [
    'Manual del Muchacho-Seguidores de la Senda',
  ],
  'Pioneros': [
    'Manual del Muchacho - Pioneros',
  ],
};

// Division -> carpeta -> premios. Si el valor de una carpeta es otro objeto en
// vez de una lista, es que lleva subcarpetas dentro (las guias semanales van
// por senda y por trimestre).
export const ARBOL_ASCENSO = {
  'Exploradores': {
    'Premios de Destreza - Plata': [
      'Administracion de granjas y haciendas',
      'Albañilería',
      'Arqueria Avanzada',
      'Arquitectura paisajística',
      'Arquitectura',
      'Artes gráficas',
      'Atletismo en pista',
      'Botes de motor',
      'Buceo con tanque de oxígeno',
      'Buceo sin tanque de oxígeno',
      'Campamento de invierno',
      'Ciclismo de montaña',
      'Ciencia solar',
      'Cinematografía',
      'Conservación del suelo y el agua',
      'Cría de animales',
      'Curtido de cueros',
      'Derecho',
      'Dibujantes',
      'Dramas y ceremonias',
      'Economía',
      'Educación para la caza sin riesgo',
      'Electricidad',
      'Electrónica',
      'Energía Atómica',
      'Escalada en Roca',
      'Esquiando',
      'Esquí Acuático',
      'Excursionismo Avanzado',
      'Explorador del Aire',
      'Geología',
      'Golf',
      'Idioma extranjero',
      'Ingeniería',
      'Instructor de Seguridad en el Agua',
      'Lectura de la Biblia',
      'Lenguaje de señas',
      'Mamíferos',
      'Mecánica Agricola',
      'Mecánica Automotriz',
      'Medicina Veterinaria',
      'Medicina',
      'Metalurgia',
      'Misiones Domesticas Construccion',
      'Misiones Juveniles',
      'Misiones Mundiales Construccion',
      'Misiones Mundiales',
      'Navegando en Bote',
      'Navegando en Kayak',
      'Navegando',
      'Oceanografia',
      'Odontologia',
      'Periodismo',
      'Pesca con Mosca',
      'Plomeria',
      'Quimica',
      'Rafting',
      'Salud pública',
      'Seguridad en el Trafico',
      'Sobrevivencia en la Selva',
      'Tabla sobre nieve',
      'Topografia',
      'Trabajo en Madera',
    ],
    'Premios de Liderazgo - Celeste': [
      'Premio de Liderazgo 301',
      'Premio de Liderazgo 302',
      'Premio de Liderazgo 303',
      'Premio de Liderazgo 304',
      'Premio de Liderazgo 305',
      'Premio de Liderazgo 306',
    ],
    'Premios Requeridos': [
      'Ciudadanía',
      'Presupuesto y finanzas',
      'Verdades Fundamentales',
    ],
    'Retos Espirituales': [
      '1 La Biblia es única',
      '10 Amor por la Biblia',
      '100 La creación de Dios',
      '101 Dios tiene el control',
      '102 La vida es breve',
      '103 La vida es preciosa',
      '104 La muerte del creyente',
      '105 La muerte de un no creyente',
      '106 El hijo no nacido',
      '107 La tragedia del suicidio',
      '108 La verdad absoluta',
      '109 Relativismo',
      '11 Mandamientos en el corazón',
      '110 La ética de la situación',
      '111 Los sentimientos',
      '112 La batalla por tus pensamientos',
      '113 Consecuencias de la conducta',
      '114 Los criterios bíblicos',
      '115 Venciendo el mal con el bien',
      '116 Pecado por omisión',
      '117 Derechos individuales',
      '118 Cuando los líderes fallan',
      '119 La misión de la Iglesia P1',
      '12 Palabras de consuelo',
      '120 La misión de la iglesia P2',
      '121 El evangelio de la prosperidad',
      '122 Libertad cristiana',
      '123 Divorciarse y volver a casarse',
      '124 La comunión',
      '125 El bautismo con agua',
      '126 Tendencias en la adoración',
      '127 Hablar en lenguas',
      '128 Espiritualmente alerta',
      '129 Satanás es real',
      '13 Promesa de vida',
      '130 Demonios Parte 1',
      '131 Demonios Parte 2',
      '132 Halloween y los demonios',
      '133 Ocultismo',
      '134 Falsa religión',
      '135 Falsos profetas',
      '136 El engaño de la Nueva Era',
      '137 Cultos',
      '138 El espíritu del anticristo',
      '139 Los últimos días',
      '14 Tomando decisiones',
      '140 Apostasía',
      '141 El Regreso de Cristo P1',
      '142 El Regreso de Cristo P2',
      '143 Ceremonia de recompensas',
      '144 La cena de la boda',
      '145 El juicio de los pecadores',
      '146 La Nueva Jerusalén',
      '147 Nuevo Cielo y nueva Tierra',
      '148 El Cielo',
      '149 El final de los tiempos',
      '15 Vida eterna',
      '150 Pensamientos finales',
      '16 Decisiones que cambian vidas',
      '17 Decisiones, decisiones',
      '18 Quitarse la vieja naturaleza',
      '19 Siete promesas',
      '2 Libro indestructible',
      '20 La nueva naturaleza',
      '21 La función del Espíritu Santo',
      '22 Por qué negarse a sí mismo',
      '23 Prioridades espirituales',
      '24 La Palabra de Dios',
      '25 Orar todos los días',
      '26 Estar lleno del Espíritu Santo',
      '27 Comparte los dones espirituales',
      '28 La voluntad de Dios Parte 1',
      '29 La voluntad de Dios Parte 2',
      '3 Libro unificado',
      '30 Tu elección la voluntad de Dios',
      '31 La voluntad de Dios para todos',
      '32 El llamado de Dios',
      '33 Desobediencia',
      '34 Servicio cristiano',
      '35 La Comunión',
      '36 La oración creativa',
      '37 Inspirar a los demás',
      '38 Misiones ahora',
      '39 Dar con generosidad',
      '4 Dos libros en Uno',
      '40 La familia es idea de Dios',
      '41 Cosas en común',
      '42 Una relación por pacto',
      '43 Hogares felices',
      '44 Hogares que sufren',
      '45 Hacerse responsable',
      '46 Apoyarse los unos a los otros',
      '47 Crisis familiar',
      '48 Participación familiar',
      '49 Amenazas para la familia',
      '5 Transmitida y confiable',
      '50 Nuestro Padre Celestial',
      '51 Amigos',
      '52 Popularidad y presión de pares',
      '53 Una variedad de amigos',
      '54 Ser amigo',
      '55 Jesús nuestro amigo',
      '56 Fidelidad',
      '57 Cualidades que cuentan',
      '58 Datos sobre las citas de noviazgo',
      '59 Eligiendo una compañera P1',
      '6 El plan de Dios',
      '60 Eligiendo una compañera P2',
      '61 Noviazgo y amor',
      '62 El matrimonio',
      '63 Pureza en el matrimonio',
      '64 Bendiciones del matrimonio',
      '65 Homosexualidad',
      '66 El sexo es sagrado',
      '67 Salud y bienestar',
      '68 Libre de adicciones',
      '69 Controlando el apetito',
      '7 Instrumento espiritual',
      '70 Limpio de pensamiento',
      '71 Puro de conducta',
      '72 Conversaciones placenteras',
      '73 El poder de la música',
      '74 Recreación sana',
      '75 Maneja tu ira',
      '76 La engañosa seguridad del dinero',
      '77 El peso de las deudas',
      '78 Las responsabilidades de la riqueza',
      '79 Utilizando sabiamente el dinero',
      '8 Libro con respuestas',
      '80 Las responsabilidades del gobierno',
      '81 Lealtad a la patria',
      '82 Cristianos, justicia e injusticia',
      '83 Cambio social y político',
      '84 Misiones por el mundo',
      '85 Proveer a los pobres',
      '86 Ayudar a las personas con discapacidad',
      '87 Ama a tu prójimo',
      '88 Definiendo las metas de tu profesión',
      '89 Percepciones falsas y verdaderas',
      '9 Guía para la vida',
      '90 Buen trabajador',
      '91 Características para el liderazgo',
      '92 Relaciones laborales',
      '93 Abierto a la dirección de Dios Parte 1',
      '94 Abierto a la dirección de Dios Parte 2',
      '95 Llamado al ministerio Parte 1',
      '96 Llamado al ministerio Parte 2',
      '97 Considera la soltería',
      '98 Considera el matrimonio',
      '99 Creado a imagen de Dios',
    ],
  },
  'Seguidores': {
    'Premios Bíblicos - Café': [
      '01-1CORINTIOS',
      '02-1JUAN',
      '03-1PEDRO',
      '04-1TESALONICENSES',
      '05-1TIMOTEO',
      '06-2CORINTIOS',
      '07-2PEDRO',
      '08-2TESALONICENSES',
      '09-2TIMOTEO',
      '10-2y3JUAN-JUDAS',
      '11-APOCALIPSIS',
      '12-COLOSENSES',
      '13-EFESIOS',
      '14-FILEMON',
      '15-FILIPENSES',
      '16-GALATAS',
      '17-HEBREOS',
      '18-ISAIAS',
      '19-JEREMIAS',
      '20-PROVERBIOS',
      '21-ROMANOS',
      '22-SALMOS',
      '23-SANTIAGO',
      '24-TITO',
    ],
    'Premios de Destreza - Verde': [
      'Academicos',
      'Alfareria',
      'Arqueria',
      'Aviacion',
      'Baloncesto',
      'Beisbol',
      'Botanica',
      'Caminatas',
      'Campismo',
      'Canoa',
      'Carpintería',
      'Ciclismo',
      'Ciencias Ambientales',
      'Cocinando en Olla Holandesa',
      'Computadoras',
      'Comunicaciones',
      'Conociendo la Discapacidad Avanzado',
      'Corneta',
      'Deportes',
      'El arte de vender',
      'Energia',
      'Equitacion',
      'Estudio de la naturaleza',
      'Estudio de los reptiles',
      'Excursiones',
      'Filatelia',
      'Fotografia',
      'Futbol',
      'Hablar en Público',
      'Historia de la Iglesia',
      'Jardineria',
      'Lectura de la Biblia',
      'Lucha Libre',
      'Manualidades en cuero',
      'Misiones Cristianas',
      'Natacion',
      'Natación Avanzada',
      'Orientación con Brújula',
      'Patineta',
      'Pionerismo',
      'Preparacion en las emergencias',
      'Prevencion del Crimen',
      'Primeros Auxilios-RCP',
      'Radio Aficionado',
      'Refugios primitivos',
      'Reparaciones en el hogar',
      'Salvavidas',
      'Seguridad en caso de incendios',
      'Seguridad en el Campamento',
      'Seguridad en el Hogar',
      'Servicio Cristiano',
      'Servicio Internacional',
      'Silvicultura',
      'Soltero',
      'Tallado en Madera',
      'Tenis',
      'Titiritero',
      'Trampas Primitivas',
      'Transporte de Vehiculos Pesados',
    ],
    'Guías Semanales': {
      'Senda de Bronce': {
        'Trimestre 1': [
          'SS-A1T1S1',
          'SS-A1T1S10',
          'SS-A1T1S11',
          'SS-A1T1S12',
          'SS-A1T1S2',
          'SS-A1T1S3',
          'SS-A1T1S4',
          'SS-A1T1S5',
          'SS-A1T1S6',
          'SS-A1T1S7',
          'SS-A1T1S8',
          'SS-A1T1S9',
        ],
        'Trimestre 2': [
          'SS-A1T2S1',
          'SS-A1T2S10',
          'SS-A1T2S11',
          'SS-A1T2S12',
          'SS-A1T2S2',
          'SS-A1T2S3',
          'SS-A1T2S4',
          'SS-A1T2S5',
          'SS-A1T2S6',
          'SS-A1T2S7',
          'SS-A1T2S8',
          'SS-A1T2S9',
        ],
        'Trimestre 4': [
          'SS-A1T4S1',
          'SS-A1T4S10',
          'SS-A1T4S11',
          'SS-A1T4S12',
          'SS-A1T4S2',
          'SS-A1T4S3',
          'SS-A1T4S4',
          'SS-A1T4S5',
          'SS-A1T4S6',
          'SS-A1T4S7',
          'SS-A1T4S8',
          'SS-A1T4S9',
        ],
        'Trimestre 3': [
          'SS-A1T3S1',
          'SS-A1T3S10',
          'SS-A1T3S11',
          'SS-A1T3S12',
          'SS-A1T3S2',
          'SS-A1T3S3',
          'SS-A1T3S4',
          'SS-A1T3S5',
          'SS-A1T3S6',
          'SS-A1T3S7',
          'SS-A1T3S8',
          'SS-A1T3S9',
        ],
      },
    },
    'Premios de Liderazgo - Amarillo': [
      'Premio de Liderazgo 201',
      'Premio de Liderazgo 202',
      'Premio de Liderazgo 203',
      'Premio de Liderazgo 204',
      'Premio de Liderazgo 205',
      'Premio de Liderazgo 206',
    ],
    'Premios Requeridos': [
      'Biblia',
      'Misiones Mundiales',
      'Preparacion Fisica',
    ],
  },
  'Pioneros': {
    'Premios Bíblicos - Naranja': [
      '1 CRONICAS',
      '1 REYES',
      '1 SAMUEL',
      '2 CRONICAS',
      '2 REYES',
      '2 SAMUEL',
      'DANIEL',
      'DEUTERONOMIO',
      'ESDRAS',
      'ESTER',
      'Exodo',
      'Genesis',
      'Hechos',
      'Joel',
      'Jonas',
      'Josue',
      'Juan',
      'Jueces',
      'Lucas',
      'Marcos',
      'Mateo',
      'Nehemias',
      'Numeros',
      'Rut',
    ],
    'Premios de Destreza - Azul': [
      'Ajedrez',
      'Amarres',
      'Aplicando la Ley',
      'Artes',
      'Astronomía',
      'Brujula',
      'Ciudadanos Mayores',
      'Clima',
      'Cocinando',
      'Cohetes',
      'Colecciones',
      'Conociendo la Discapacidad',
      'Cuidado del Perro',
      'Dardos',
      'Escultura',
      'Estudio de las Aves',
      'Estudio de los Insectos',
      'Fogata',
      'Herramientas',
      'Huella Digital',
      'Iglesia',
      'La Fauna',
      'Lectura de la Biblia',
      'Lectura',
      'Lenguaje de Señas Basico',
      'Lideres Nacionales',
      'Mascotas',
      'Modelos y Diseños',
      'Musica',
      'Nudos y Cuerdas',
      'Pasatiempo',
      'Patinaje en Linea',
      'Patinaje sobre Hielo',
      'Patinaje sobre Ruedas',
      'Pesca',
      'Pintura',
      'Remo',
      'Seguridad',
      'Trenes',
      'Vida en Familia',
    ],
    'Guías Semanales': {
      'Senda de Bronce': {
        'Trimestre 1': [
          'PI-A1T1S1',
          'PI-A1T1S10',
          'PI-A1T1S11',
          'PI-A1T1S12',
          'PI-A1T1S2',
          'PI-A1T1S3',
          'PI-A1T1S4',
          'PI-A1T1S5',
          'PI-A1T1S6',
          'PI-A1T1S7',
          'PI-A1T1S8',
          'PI-A1T1S9',
        ],
        'Trimestre 2': [
          'PI-A1T2S1',
          'PI-A1T2S10',
          'PI-A1T2S11',
          'PI-A1T2S12',
          'PI-A1T2S2',
          'PI-A1T2S3',
          'PI-A1T2S4',
          'PI-A1T2S5',
          'PI-A1T2S6',
          'PI-A1T2S7',
          'PI-A1T2S8',
          'PI-A1T2S9',
        ],
        'Trimestre 3': [
          'PI-A1T3S1',
          'PI-A1T3S10',
          'PI-A1T3S11',
          'PI-A1T3S12',
          'PI-A1T3S2',
          'PI-A1T3S3',
          'PI-A1T3S4',
          'PI-A1T3S5',
          'PI-A1T3S6',
          'PI-A1T3S7',
          'PI-A1T3S8',
          'PI-A1T3S9',
        ],
        'Trimestre 4': [
          'PI-A1T4S1',
          'PI-A1T4S10',
          'PI-A1T4S11',
          'PI-A1T4S12',
          'PI-A1T4S2',
          'PI-A1T4S3',
          'PI-A1T4S4',
          'PI-A1T4S5',
          'PI-A1T4S6',
          'PI-A1T4S7',
          'PI-A1T4S8',
          'PI-A1T4S9',
        ],
      },
    },
    'Premios de Liderazgo - Rojo': [
      'Premio de Liderazgo 101',
      'Premio de Liderazgo 102',
      'Premio de Liderazgo 103',
      'Premio de Liderazgo 104',
      'Premio de Liderazgo 105',
      'Premio de Liderazgo 106',
    ],
    'Premios Requeridos': [
      'Biblia-REQUERIDO',
      'Misiones Mundiales-REQUERIDO',
      'Primeros Auxilios-REQUERIDO',
    ],
  },
};

// ----------------------------------------------------------------------
// Del arbol de arriba a los nodos planos que consume la aplicacion: cada uno con
// su id, su nombre y el padre del que cuelga.
// ----------------------------------------------------------------------

const nodoBase = (id, name, parentId, type) => ({
  id,
  name,
  type,
  parentId,
  size: 0,
  totalFiles: 0,
  shared: [],
  isFavorited: false,
  createdAt: new Date(),
  modifiedAt: null,
  tags: [],
});

export function construirNodosAscenso() {
  const nodos = [];

  DIVISIONES_ASCENSO.forEach(({ nombre, sigla }) => {
    const idDivision = idDeRutaAscenso(nombre);

    nodos.push({
      id: idDivision,
      name: nombre,
      type: 'folder',
      parentId: ID_RAIZ_SISTEMA_ASCENSO,
      target: sigla,
      total: 0,
      completed: 0,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    });

    (PREMIOS_EN_RAIZ_ASCENSO[nombre] || []).forEach((premio) => {
      nodos.push(nodoBase(idDeRutaAscenso(nombre, premio), premio, idDivision, 'pdf'));
    });

    const recorrer = (contenido, rutaPadre, idPadre) => {
      Object.entries(contenido).forEach(([clave, valor]) => {
        const ruta = [...rutaPadre, clave];
        const id = idDeRutaAscenso(nombre, ...ruta);

        nodos.push(nodoBase(id, clave, idPadre, 'folder'));

        if (Array.isArray(valor)) {
          valor.forEach((premio) => {
            nodos.push(nodoBase(idDeRutaAscenso(nombre, ...ruta, premio), premio, id, 'pdf'));
          });

          return;
        }

        recorrer(valor, ruta, id);
      });
    };

    recorrer(ARBOL_ASCENSO[nombre] || {}, [], idDivision);
  });

  return nodos;
}
