export const ROLES = {
  USUARIO_COMUN: 'usuario_comun',
  USUARIO_DESTACAMENTO: 'usuario_destacamento',
  USUARIO_DESTACAMENTO_ASISTENTE: 'usuario_destacamento_asistente',
  // Cargos de nivel destacamento (mismo perfil operativo que el Coordinador).
  PASTOR_DESTACAMENTO: 'pastor_destacamento',
  CONSEJO_DESTACAMENTO: 'consejo_destacamento',
  CAPELLAN_DESTACAMENTO: 'capellan_destacamento',
  LIDER_GRUPO: 'lider_grupo',
  LIDER_ASISTENTE_GRUPO: 'lider_asistente_grupo',
  USUARIO_SECCION: 'usuario_seccion',
  USUARIO_SECCION_ASISTENTE: 'usuario_seccion_asistente',
  COORDINADOR_ADIESTRAMIENTO_SECCION: 'coordinador_adiestramiento_seccion',
  COORDINADOR_PROMOCION_SECCION: 'coordinador_promocion_seccion',
  COORDINADOR_PRODUCCION_SECCION: 'coordinador_produccion_seccion',
  COORDINADOR_PROGRAMA_SECCION: 'coordinador_programa_seccion',
  USUARIO_REGION: 'usuario_region',
  USUARIO_REGION_ASISTENTE: 'usuario_region_asistente',
  COORDINADOR_ADIESTRAMIENTO_REGION: 'coordinador_adiestramiento_region',
  COORDINADOR_PROMOCION_REGION: 'coordinador_promocion_region',
  COORDINADOR_PRODUCCION_REGION: 'coordinador_produccion_region',
  COORDINADOR_PROGRAMA_REGION: 'coordinador_programa_region',
  CONSEJO_NACIONAL: 'consejo_nacional',
  // Cargos del Consejo Nacional (alcance nacional, solo lectura). Todos ven todo
  // excepto menores; Director Nacional ademas ve menores.
  MINISTERIOS_INFANTILES_NACIONAL: 'ministerios_infantiles_nacional',
  DIRECTOR_NACIONAL: 'director_nacional',
  CAPELLAN_NACIONAL: 'capellan_nacional',
  COORDINADOR_ADIESTRAMIENTO_NACIONAL: 'coordinador_adiestramiento_nacional',
  SUBDIRECTOR_NACIONAL: 'subdirector_nacional',
  COORDINADOR_PROMOCION_NACIONAL: 'coordinador_promocion_nacional',
  COORDINADOR_PRODUCCION_NACIONAL: 'coordinador_produccion_nacional',
  COORDINADOR_PROGRAMA_NACIONAL: 'coordinador_programa_nacional',
  COMITES_ESPECIALES_NACIONAL: 'comites_especiales_nacional',
  OFICIALES_ADIESTRAMIENTOS_ESPECIALES_NACIONAL: 'oficiales_adiestramientos_especiales_nacional',
  CONSEJO_EJECUTIVO: 'consejo_ejecutivo',

  ADMINISTRADOR_GLOBAL: 'administrador_global',
  ADMINISTRADOR_FUNCIONAL: 'administrador_funcional',
  ADMINISTRADOR_TIENDA: 'administrador_tienda',
};

export const ALCANCES = {
  DESTACAMENTO: 'destacamento',
  SECCION: 'seccion',
  REGION: 'region',
  NACIONAL: 'nacional',
  GLOBAL: 'global',
};

export const ROLES_CATALOGO = [
  {
    codigo: ROLES.USUARIO_COMUN,
    nombre: 'Usuario Comun',
    descripcion: 'Acceso basico a su destacamento y datos publicos de destacamentos de su seccion.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_DESTACAMENTO,
    nombre: 'Coordinador de Destacamento',
    descripcion: 'Gestion operativa de miembros y documentos dentro de un destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_DESTACAMENTO_ASISTENTE,
    nombre: 'Coordinador Asistente de Destacamento',
    descripcion: 'Apoyo del Coordinador de Destacamento; mismo alcance y tareas operativas diarias.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.PASTOR_DESTACAMENTO,
    nombre: 'Pastor',
    descripcion: 'Cargo del destacamento con el mismo alcance operativo que el Coordinador de Destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.CONSEJO_DESTACAMENTO,
    nombre: 'Consejo Destacamento',
    descripcion: 'Cargo del destacamento con el mismo alcance operativo que el Coordinador de Destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.CAPELLAN_DESTACAMENTO,
    nombre: 'Capellán',
    descripcion: 'Cargo del destacamento con el mismo alcance operativo que el Coordinador de Destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.LIDER_GRUPO,
    nombre: 'Líder de Grupo',
    descripcion: 'Cargo del destacamento con el mismo alcance operativo que el Coordinador de Destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.LIDER_ASISTENTE_GRUPO,
    nombre: 'Líder Asistente de Grupo',
    descripcion: 'Cargo del destacamento con el mismo alcance operativo que el Coordinador de Destacamento.',
    alcancePredeterminado: ALCANCES.DESTACAMENTO,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_SECCION,
    nombre: 'Coordinador Seccional',
    descripcion: 'Supervision de destacamentos y miembros adultos dentro de una seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_SECCION_ASISTENTE,
    nombre: 'Sub-Coordinador Seccional',
    descripcion: 'Apoyo del Coordinador Seccional; crea y edita destacamentos de su seccion sin editar la seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_ADIESTRAMIENTO_SECCION,
    nombre: 'Coordinador de Adiestramiento',
    descripcion: 'Coordinador de area (adiestramiento) con alcance de consulta dentro de una seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROMOCION_SECCION,
    nombre: 'Coordinador de Promoción',
    descripcion: 'Coordinador de area (promocion) con alcance de consulta dentro de una seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PRODUCCION_SECCION,
    nombre: 'Coordinador de Producción',
    descripcion: 'Coordinador de area (produccion) con alcance de consulta dentro de una seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROGRAMA_SECCION,
    nombre: 'Coordinador de Programa',
    descripcion: 'Coordinador de area (programa) con alcance de consulta dentro de una seccion.',
    alcancePredeterminado: ALCANCES.SECCION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_REGION,
    nombre: 'Coordinador Regional',
    descripcion: 'Supervision regional de secciones, destacamentos e indicadores.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.USUARIO_REGION_ASISTENTE,
    nombre: 'Sub-Director Regional',
    descripcion: 'Apoyo del Director Regional; crea y edita secciones y edita destacamentos sin editar la region.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_ADIESTRAMIENTO_REGION,
    nombre: 'Coordinador de Adiestramiento',
    descripcion: 'Coordinador de area (adiestramiento) con alcance de consulta dentro de una region.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROMOCION_REGION,
    nombre: 'Coordinador de Promoción',
    descripcion: 'Coordinador de area (promocion) con alcance de consulta dentro de una region.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PRODUCCION_REGION,
    nombre: 'Coordinador de Producción',
    descripcion: 'Coordinador de area (produccion) con alcance de consulta dentro de una region.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROGRAMA_REGION,
    nombre: 'Coordinador de Programa',
    descripcion: 'Coordinador de area (programa) con alcance de consulta dentro de una region.',
    alcancePredeterminado: ALCANCES.REGION,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.CONSEJO_NACIONAL,
    nombre: 'Consejo Nacional',
    descripcion: 'Consulta estrategica nacional para cargos organizacionales de nivel zonal hacia arriba.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.MINISTERIOS_INFANTILES_NACIONAL,
    nombre: 'Ministerios Infantiles',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.DIRECTOR_NACIONAL,
    nombre: 'Director Nacional',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional, incluyendo miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.CAPELLAN_NACIONAL,
    nombre: 'Capellán Nacional',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_ADIESTRAMIENTO_NACIONAL,
    nombre: 'Coordinador Nacional de Adiestramiento',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.SUBDIRECTOR_NACIONAL,
    nombre: 'Sub-Director Nacional',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROMOCION_NACIONAL,
    nombre: 'Coordinador Nacional de Promoción',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PRODUCCION_NACIONAL,
    nombre: 'Coordinador Nacional de Producción',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COORDINADOR_PROGRAMA_NACIONAL,
    nombre: 'Coordinador Nacional de Programa',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.COMITES_ESPECIALES_NACIONAL,
    nombre: 'Comités Especiales',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.OFICIALES_ADIESTRAMIENTOS_ESPECIALES_NACIONAL,
    nombre: 'Oficiales de Adiestramientos Especiales',
    descripcion: 'Consejo Nacional: ve todo a nivel nacional excepto miembros menores de edad.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.CONSEJO_EJECUTIVO,
    nombre: 'Consejo Ejecutivo',
    descripcion: 'Consulta nacional completa sin modificacion directa de informacion.',
    alcancePredeterminado: ALCANCES.NACIONAL,
    asignableDesdeAdministradores: true,
    activo: true,
  },
  {
    codigo: ROLES.ADMINISTRADOR_GLOBAL,
    nombre: 'Administrador Global',
    descripcion: 'Control total de la plataforma.',
    alcancePredeterminado: ALCANCES.GLOBAL,
    asignableDesdeAdministradores: false,
    activo: true,
  },
  {
    codigo: ROLES.ADMINISTRADOR_FUNCIONAL,
    nombre: 'Administrador Funcional',
    descripcion: 'Mantenimiento, respaldo, configuracion y correos sin acceso administrativo a tienda.',
    alcancePredeterminado: ALCANCES.GLOBAL,
    asignableDesdeAdministradores: false,
    activo: true,
  },
  {
    codigo: ROLES.ADMINISTRADOR_TIENDA,
    nombre: 'Administrador de Gestion de Tienda',
    descripcion: 'Gestion comercial de productos, ventas, ordenes e inventario.',
    alcancePredeterminado: ALCANCES.GLOBAL,
    asignableDesdeAdministradores: false,
    activo: true,
  },
];

export const ROLES_ASIGNABLES_CATALOGO = ROLES_CATALOGO.filter(
  (rol) => rol.asignableDesdeAdministradores
);

export const ROLES_POR_CODIGO = Object.fromEntries(ROLES_CATALOGO.map((rol) => [rol.codigo, rol]));
