import { construirNodosAscenso } from 'src/catalogs/sistema-ascenso';

// ----------------------------------------------------------------------
// EL ARBOL DE PREMIOS QUE VE LA APLICACION.
//
// Son dos sistemas colgando de la misma raiz: el Sistema de Ascenso, que llevan
// los muchachos por divisiones, y la Academia Ministerial, que llevan los
// lideres. Lo lee la ficha del miembro y tambien el selector de rutas de los
// certificados automaticos, asi que lo que se anada aqui aparece en los dos.
//
// El Sistema de Ascenso NO se escribe a mano: sale de `src/catalogs/sistema-ascenso`,
// que es la transcripcion del inventario oficial. Para anadir un premio se toca
// ese catalogo, no este archivo. Aqui quedan Navegantes y la Academia, que no
// vienen de ese inventario.
// ----------------------------------------------------------------------

export const _awards = [

  // =============================
  // RAIZ
  // =============================
    {
      id: "sistema-de-ascenso",
      name: "Sistema de Ascenso",
      type: "folder",
      parentId: null,
      target: "Muchachos",
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "academia-ministerial",
      name: "Academia Ministerial",
      type: "folder",
      parentId: null,
      target: "Líderes",
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },

  // =============================
  // NAVEGANTES
  // =============================
    {
      id: "navegantes",
      name: "Navegantes",
      type: "folder",
      parentId: "sistema-de-ascenso",
      target: "NV",
      total: 0,
      completed: 0,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "guia-semanal",
      name: "Guía Semanal",
      type: "folder",
      parentId: "navegantes",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "senda-de-bronce-navegantes",
      name: "Senda de Bronce",
      type: "folder",
      parentId: "guia-semanal",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-1---bronce-navegantes",
      name: "Trimestre 1",
      type: "folder",
      parentId: "senda-de-bronce-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "leccion-1---t1-bronce",
      name: "Lección 1",
      type: "pdf",
      parentId: "trimestre-1---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-2---t1-bronce",
      name: "Lección 2",
      type: "pdf",
      parentId: "trimestre-1---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-3---t1-bronce",
      name: "Lección 3",
      type: "pdf",
      parentId: "trimestre-1---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-4---t1-bronce",
      name: "Lección 4",
      type: "pdf",
      parentId: "trimestre-1---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-5---t1-bronce",
      name: "Lección 5",
      type: "pdf",
      parentId: "trimestre-1---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "trimestre-2---bronce-navegantes",
      name: "Trimestre 2",
      type: "folder",
      parentId: "senda-de-bronce-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "leccion-1---t2-bronce",
      name: "Lección 1",
      type: "pdf",
      parentId: "trimestre-2---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-2---t2-bronce",
      name: "Lección 2",
      type: "pdf",
      parentId: "trimestre-2---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-3---t2-bronce",
      name: "Lección 3",
      type: "pdf",
      parentId: "trimestre-2---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-4---t2-bronce",
      name: "Lección 4",
      type: "pdf",
      parentId: "trimestre-2---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-5---t2-bronce",
      name: "Lección 5",
      type: "pdf",
      parentId: "trimestre-2---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "trimestre-3---bronce-navegantes",
      name: "Trimestre 3",
      type: "folder",
      parentId: "senda-de-bronce-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "leccion-1---t3-bronce",
      name: "Lección 1",
      type: "pdf",
      parentId: "trimestre-3---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-2---t3-bronce",
      name: "Lección 2",
      type: "pdf",
      parentId: "trimestre-3---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-3---t3-bronce",
      name: "Lección 3",
      type: "pdf",
      parentId: "trimestre-3---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-4---t3-bronce",
      name: "Lección 4",
      type: "pdf",
      parentId: "trimestre-3---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-5---t3-bronce",
      name: "Lección 5",
      type: "pdf",
      parentId: "trimestre-3---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "trimestre-4---bronce-navegantes",
      name: "Trimestre 4",
      type: "folder",
      parentId: "senda-de-bronce-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "leccion-1---t4-bronce",
      name: "Lección 1",
      type: "pdf",
      parentId: "trimestre-4---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-2---t4-bronce",
      name: "Lección 2",
      type: "pdf",
      parentId: "trimestre-4---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-3---t4-bronce",
      name: "Lección 3",
      type: "pdf",
      parentId: "trimestre-4---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-4---t4-bronce",
      name: "Lección 4",
      type: "pdf",
      parentId: "trimestre-4---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "leccion-5---t4-bronce",
      name: "Lección 5",
      type: "pdf",
      parentId: "trimestre-4---bronce-navegantes",
      createdAt: new Date(),
    },
    {
      id: "senda-de-plata-navegantes",
      name: "Senda de Plata",
      type: "folder",
      parentId: "guia-semanal",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-1---plata-navegantes",
      name: "Trimestre 1",
      type: "folder",
      parentId: "senda-de-plata-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-2---plata-navegantes",
      name: "Trimestre 2",
      type: "folder",
      parentId: "senda-de-plata-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-3---plata-navegantes",
      name: "Trimestre 3",
      type: "folder",
      parentId: "senda-de-plata-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-4---plata-navegantes",
      name: "Trimestre 4",
      type: "folder",
      parentId: "senda-de-plata-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "senda-de-oro-navegantes",
      name: "Senda de Oro",
      type: "folder",
      parentId: "guia-semanal",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-1---oro-navegantes",
      name: "Trimestre 1",
      type: "folder",
      parentId: "senda-de-oro-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-2---oro-navegantes",
      name: "Trimestre 2",
      type: "folder",
      parentId: "senda-de-oro-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-3---oro-navegantes",
      name: "Trimestre 3",
      type: "folder",
      parentId: "senda-de-oro-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "trimestre-4---oro-navegantes",
      name: "Trimestre 4",
      type: "folder",
      parentId: "senda-de-oro-navegantes",
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },

  // =============================
  // ACADEMIA MINISTERIAL
  // =============================
    {
      id: "lider-juvenil",
      name: "Líder Juvenil",
      type: "folder",
      parentId: "academia-ministerial",
      required: "Sí",
      total: 0,
      completed: 0,
      updatedAt: null,
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "campamento-de-barras-doradas",
      name: "Campamento de Barras Doradas",
      type: "pdf",
      parentId: "lider-juvenil",
      createdAt: new Date(),
    },
    {
      id: "lider-de-destacamento",
      name: "Líder de Destacamento",
      type: "folder",
      parentId: "academia-ministerial",
      required: "Sí",
      total: 0,
      completed: 0,
      updatedAt: null,
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "fundamentos",
      name: "Fundamentos",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "mentores",
      name: "Mentores",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "seguridad-y-primeros-auxilios",
      name: "Seguridad y Primeros Auxilios",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "destacamento-de-clase-mundial",
      name: "Destacamento de Clase Mundial",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "campamento-nacional-ministerial",
      name: "Campamento Nacional Ministerial",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "cuadro-avanzado",
      name: "Cuadro Avanzado",
      type: "pdf",
      parentId: "lider-de-destacamento",
      createdAt: new Date(),
    },
    {
      id: "lider-organizacional",
      name: "Líder Organizacional",
      type: "folder",
      parentId: "academia-ministerial",
      required: "Sí",
      total: 0,
      completed: 0,
      updatedAt: null,
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "instructor",
      name: "Instructor",
      type: "folder",
      parentId: "academia-ministerial",
      required: "Sí",
      total: 0,
      completed: 0,
      updatedAt: null,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "academia-de-jefes",
      name: "Academia de Jefes",
      type: "pdf",
      parentId: "instructor",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "academia-nacional",
      name: "Academia Nacional",
      type: "pdf",
      parentId: "instructor",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "academia-avanzada",
      name: "Academia Avanzada",
      type: "pdf",
      parentId: "instructor",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },
    {
      id: "instructor-de-academia",
      name: "Instructor de Academia",
      type: "pdf",
      parentId: "instructor",
      size: 0,
      totalFiles: 0,
      shared: [],
      isFavorited: false,
      createdAt: new Date(),
      modifiedAt: null,
      tags: [],
    },

  // =============================
  // SISTEMA DE ASCENSO
  //
  // Exploradores, Seguidores y Pioneros con sus carpetas y sus premios, tal
  // como estan en la carpeta oficial. Se construyen al vuelo desde el catalogo.
  // =============================
  ...construirNodosAscenso(),
];
