import { fSub } from 'src/utils/format-time';

import { CONFIG } from 'src/global-config';

import {
  _id,
  _ages,
  _roles,
  _memberPosition,
  _sectionalXDestMemberCounts,
  _nationalXAssignedRegionals,
  _memberPositions,
  _prices,
  _emails,
  _memberEmails,
  _regionalXSectionalEmails,
  _ratings,
  _nativeS,
  _nativeM,
  _nativeL,
  _percents,
  _booleans,
  _sentences,
  _lastNames,
  _fullNames,
  _memberFullNames,
  _destFullNames,
  _sectionalFullNames,
  _regionalFullNames,
  _nationalXMemberFullNames,
  _tourNames,
  _jobTitles,
  _taskNames,
  _fileNames,
  _postTitles,
  _firstNames,
  _eventNames,
  _courseNames,
  _fullAddress,
  _companyNames,
  _sectionalDestCounts,
  _nationalXMemberPositions,
  _destMemberCounts,
  _destMemberships,
  _regionalXSectionalCounts,
  _regionalXSectionalMemberCounts,
  _memberDivisionNames,
  _productNames,
  _descriptions,
  _phoneNumbers,
  _sectionalCoordNames,
  _nationalXMemberPhoneNumbers,
  _memberPhoneNumbers,
  _regionalDirectorNames,
  _destCoordNames,
  _countryNames,
} from './assets';

// ----------------------------------------------------------------------

export const _mock = {
  id: (index) => _id[index],
  time: (index) => fSub({ days: index, hours: index }),
  boolean: (index) => _booleans[index],
  role: (index) => _roles[index],
  memberPosition: (index) => _memberPositions[index],
  sectionalXDestMemberCount: (index) => _sectionalXDestMemberCounts[index],
  nationalXAssignedRegional: (index) => _nationalXAssignedRegionals[index],
  regionalXSectionalMemberCount: (index) => _regionalXSectionalMemberCounts[index],
  destMembership: (index) => _destMemberships[index],
  memberPosition: (index) => _memberPositions[index],
  courseNames: (index) => _courseNames[index],
  fileNames: (index) => _fileNames[index],
  eventNames: (index) => _eventNames[index],
  taskNames: (index) => _taskNames[index],
  postTitle: (index) => _postTitles[index],
  jobTitle: (index) => _jobTitles[index],
  tourName: (index) => _tourNames[index],
  productName: (index) => _productNames[index],
  sentence: (index) => _sentences[index],
  description: (index) => _descriptions[index],
  // Contact
  email: (index) => _emails[index],
  memberEmail: (index) => _memberEmails[index],
  regionalXSectionalEmail: (index) => _regionalXSectionalEmails[index],
  phoneNumber: (index) => _phoneNumbers[index],
  sectionalCoordName: (index) => _sectionalCoordNames[index],
  nationalXMemberPhoneNumber: (index) => _nationalXMemberPhoneNumbers[index],
  memberPhoneNumber: (index) => _memberPhoneNumbers[index],
  regionalDirectorName: (index) => _regionalDirectorNames[index],
  destCoordName: (index) => _destCoordNames[index],
  fullAddress: (index) => _fullAddress[index],
  // Name
  firstName: (index) => _firstNames[index],
  lastName: (index) => _lastNames[index],
  fullName: (index) => _fullNames[index],
  memberFullName: (index) => _memberFullNames[index],
  destFullName: (index) => _destFullNames[index],
  sectionalFullName: (index) => _sectionalFullNames[index],
  regionalFullName: (index) => _regionalFullNames[index],
  nationalXMemberFullName: (index) => _nationalXMemberFullNames[index],
  companyNames: (index) => _companyNames[index],
  sectionalDestCount: (index) => _sectionalDestCounts[index],
  nationalXMemberPosition: (index) => _nationalXMemberPositions[index],
  regionalXSectionalCount: (index) => _regionalXSectionalCounts[index],
  destMemberCount: (index) => _destMemberCounts[index],
  memberDivisionNames: (index) => _memberDivisionNames[index],
  countryNames: (index) => _countryNames[index],
  // Number
  number: {
    percent: (index) => _percents[index],
    rating: (index) => _ratings[index],
    age: (index) => _ages[index],
    price: (index) => _prices[index],
    nativeS: (index) => _nativeS[index],
    nativeM: (index) => _nativeM[index],
    nativeL: (index) => _nativeL[index],
  },
  // Image
  image: {
    cover: (index) => `${CONFIG.assetsDir}/assets/images/mock/cover/cover-${index + 1}.webp`,
    avatar: (index) => `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-${index + 1}.webp`,
    travel: (index) => `${CONFIG.assetsDir}/assets/images/mock/travel/travel-${index + 1}.webp`,
    course: (index) => `${CONFIG.assetsDir}/assets/images/mock/course/course-${index + 1}.webp`,
    company: (index) => `${CONFIG.assetsDir}/assets/images/mock/company/company-${index + 1}.webp`,
    product: (index) =>
      `${CONFIG.assetsDir}/assets/images/mock/m-product/product-${index + 1}.webp`,
    portrait: (index) =>
      `${CONFIG.assetsDir}/assets/images/mock/portrait/portrait-${index + 1}.webp`,
  },
};
