// ----------------------------------------------------------------------

export const _id = Array.from(
  { length: 40 },
  (_, index) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index + 1}`
);

// ----------------------------------------------------------------------

export const _booleans = [
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  true,
];

// ----------------------------------------------------------------------

export const _prices = [
  83.74, 97.14, 68.71, 85.21, 52.17, 25.18, 43.84, 60.98, 98.42, 53.37, 72.75, 56.61, 64.55, 77.32,
  60.62, 79.81, 93.68, 47.44, 76.24, 92.87, 72.91, 20.54, 94.25, 37.51,
];

export const _ratings = [
  4.2, 3.7, 4.5, 3.5, 0.5, 3.0, 2.5, 2.8, 4.9, 3.6, 2.5, 1.7, 3.9, 2.8, 4.1, 4.5, 2.2, 3.2, 0.6,
  1.3, 3.8, 3.8, 3.8, 2.0,
];

export const _ages = [
  30, 26, 59, 47, 29, 46, 18, 56, 39, 19, 45, 18, 46, 56, 38, 41, 44, 48, 32, 45, 42, 60, 33, 57,
];

export const _percents = [
  10.1, 13.6, 28.2, 42.1, 37.2, 18.5, 40.1, 94.8, 91.4, 53.0, 25.4, 62.9, 86.6, 62.4, 35.4, 17.6,
  52.0, 6.8, 95.3, 26.6, 69.9, 92.1, 46.2, 85.6,
];

export const _nativeS = [
  11, 10, 7, 10, 12, 5, 10, 1, 8, 8, 10, 11, 12, 8, 4, 11, 8, 9, 4, 9, 2, 6, 3, 7,
];

export const _nativeM = [
  497, 763, 684, 451, 433, 463, 951, 194, 425, 435, 807, 521, 538, 839, 394, 269, 453, 821, 364,
  849, 804, 776, 263, 239,
];

export const _nativeL = [
  9911, 1947, 9124, 6984, 8488, 2034, 3364, 8401, 8996, 5271, 8478, 1139, 8061, 3035, 6733, 3952,
  2405, 3127, 6843, 4672, 6995, 6053, 5192, 9686,
];

export const _fullAddress = [
  `19034 Verna Unions Apt. 164 - Honolulu, RI / 87535`,
  `1147 Rohan Drive Suite 819 - Burlington, VT / 82021`,
  `18605 Thompson Circle Apt. 086 - Idaho Falls, WV / 50337`,
  `110 Lamar Station Apt. 730 - Hagerstown, OK / 49808`,
  `36901 Elmer Spurs Apt. 762 - Miramar, DE / 92836`,
  `2089 Runolfsson Harbors Suite 886 - Chapel Hill, TX / 32827`,
  `279 Karolann Ports Apt. 774 - Prescott Valley, WV / 53905`,
  `96607 Claire Square Suite 591 - St. Louis Park, HI / 40802`,
  `9388 Auer Station Suite 573 - Honolulu, AK / 98024`,
  `47665 Adaline Squares Suite 510 - Blacksburg, NE / 53515`,
  `989 Vernice Flats Apt. 183 - Billings, NV / 04147`,
  `91020 Wehner Locks Apt. 673 - Albany, WY / 68763`,
  `585 Candelario Pass Suite 090 - Columbus, LA / 25376`,
  `80988 Renner Crest Apt. 000 - Fargo, VA / 24266`,
  `28307 Shayne Pike Suite 523 - North Las Vegas, AZ / 28550`,
  `205 Farrell Highway Suite 333 - Rock Hill, OK / 63421`,
  `253 Kara Motorway Suite 821 - Manchester, SD / 09331`,
  `13663 Kiara Oval Suite 606 - Missoula, AR / 44478`,
  `8110 Claire Port Apt. 703 - Anchorage, TN / 01753`,
  `4642 Demetris Lane Suite 407 - Edmond, AZ / 60888`,
  `74794 Asha Flat Suite 890 - Lancaster, OR / 13466`,
  `8135 Keeling Pines Apt. 326 - Alexandria, MA / 89442`,
  `441 Gibson Shores Suite 247 - Pasco, NM / 60678`,
  `4373 Emelia Valley Suite 596 - Columbia, NM / 42586`,
];

// ----------------------------------------------------------------------

export const _emails = [
  'jose.perez01@gmail.com',
  'carlos.rodriguez02@hotmail.com',
  'diana.martinez03@yahoo.com',
  'juan.gomez04@gmail.com',
  'rafael.jimenez05@hotmail.com',
  'laura.hernandez06@gmail.com',
  'cristopher.cardenas07@yahoo.com',
  'melanie.nunez08@gmail.com',
  'luis.santana09@hotmail.com',
  'shawn.delacruz10@gmail.com',
  'soren.duran11@yahoo.com',
  'cortez.herrera12@gmail.com',
  'brycen.jimenez13@hotmail.com',
  'giana.batista14@gmail.com',
  'aspen.reyes15@yahoo.com',
  'colten.aguilar16@gmail.com',
  'angelica.moralesotmail.com',
  'selina.nunez18@gmail.com',
  'lawson.baez19@yahoo.com',
  'ariana.pena20@gmail.com',
  'amiah.garcia21@hotmail.com',
  'harold.sanchez22@gmail.com',
  'esperanza.martinez23@yahoo.com',
  'mireya.concepcion24@hotmail.com',
];


// ----------------------------------------------------------------------

export const _fullNames = [
  `Jayvion Simon`,
  `Lucian Obrien`,
  `Deja Brady`,
  `Harrison Stein`,
  `Reece Chung`,
  `Lainey Davidson`,
  `Cristopher Cardenas`,
  `Melanie Noble`,
  `Chase Day`,
  `Shawn Manning`,
  `Soren Durham`,
  `Cortez Herring`,
  `Brycen Jimenez`,
  `Giana Brandt`,
  `Aspen Schmitt`,
  `Colten Aguilar`,
  `Angelique Morse`,
  `Selina Boyer`,
  `Lawson Bass`,
  `Ariana Lang`,
  `Amiah Pruitt`,
  `Harold Mcgrath`,
  `Esperanza Mcintyre`,
  `Mireya Conner`,
];

/* ----------------------- MEMBERS DOWN-----------------------*/

export const MEMBERS = [
  {
    id: 'member-01',
    firstName: 'Roderi',
    lastName: 'Peña',
    avatarUrl: '/assets/images/avatars/members/member-01.jpg',
    memberAddress: 'Ciudad Juan Bosch, Sembrador VIII, Edificio 2',
    birthDate: '2000-06-18',
    email: 'roderi.pena@gmail.com',
    phoneNumber: '+18297878833',
    province: 'Santo Domingo Este',
    city: 'Santo Domingo',

    ocupation: 'Ing. Software',
    gender: 'M',
    shirtSize: 'M',

    memberDivision: 'Liderazgo',
    destId: 'dest-018',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-central',
    status: 'active',

  },
  //actualizado
  {
    id: 'member-02',
    fullName: 'Carloss Alberto Rodríguez',
    avatarUrl: '/assets/images/avatars/members/member-02.jpg',
    memberAddress: 'Calle Constitución #19, San Cristóbal',
    birthDate: '1998-03-14',
    email: 'carlos.rodriguez02@hotmail.com',
    phoneNumber: '+18295550198',
    province: 'Distrito Nacional',
    city: 'Distrito Nacional',

    memberDivision: 'Liderazgo',

    destId: 'dest-02',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-este',

    status: 'active',
  },
  {
    id: 'member-03',
    fullName: 'María Fernanda Martínez',
    memberAddress: 'Calle Hermanas Mirabal #22, Santo Domingo Norte',
    birthDate: '2007-08-02',
    email: 'diana.martinez03@yahoo.com',
    phoneNumber: '+18495550958',
    province: 'Santiago',
    city: 'Santiago',
    memberDivision: 'Exploradores',
    destId: 'dest-03',
    sectionalId: 'sec-este-02',
    regionalId: 'reg-este',
    status: 'active',
  },
  {
    id: 'member-04',
    fullName: 'Pedro Julio Sepúlveda',
    avatarUrl: '/assets/images/avatars/members/member-04.jpg',
    memberAddress: 'Av. Isabel Aguiar #145, Santo Domingo Oeste',
    birthDate: '2005-11-19',
    email: 'juan.gomez04@gmail.com',
    phoneNumber: '+18095555432',
    province: 'Santo Domingo',
    city: 'Santo Domingo Este',
    memberDivision: 'Pioneros',
    destId: 'dest-04',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-central',
    status: 'active',
  },
  {
    id: 'member-05',
    fullName: 'Juan Ramón Corporán',
    avatarUrl: '/assets/images/avatars/members/member-05.jpg',
    memberAddress: 'Av. Juan Pablo Duarte #56, Santiago',
    birthDate: '1990-01-10',
    email: 'juan.ramon@hotmail.com',
    phoneNumber: '+18295555678',
    province: 'Santo Domingo',
    city: 'San Cristóbal',
    memberDivision: 'Exploradores',
    destId: 'dest-05',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-central',
    status: 'active',
  },
  {
    id: 'member-06',
    fullName: 'Laura Sofía Hernández',
    memberAddress: 'Calle Benito González #31, Distrito Nacional',
    birthDate: '2003-06-30',
    email: 'laura.hernandez06@gmail.com',
    phoneNumber: '+18495553456',
    province: 'La Altagracia',
    city: 'Higüey',
    memberDivision: 'Navegantes',
    destId: 'dest-06',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-este',
    status: 'active',
  },
  {
    id: 'member-07',
    fullName: 'Cristopher Cárdenas',
    memberAddress: 'Calle Duarte #73, La Vega',
    birthDate: '2009-09-12',
    email: 'cristopher.cardenas07@yahoo.com',
    phoneNumber: '+18095556789',
    province: 'Santo Domingo',
    city: 'Santo Domingo Norte',
    memberDivision: 'Exploradores',
    destId: 'dest-07',
    sectionalId: 'sec-este-02',
    regionalId: 'reg-este',
    status: 'active',
  },
  {
    id: 'member-08',
    fullName: 'Alejandro Terrero',
    avatarUrl: '/assets/images/avatars/members/member-08.jpg',
    memberAddress: 'Calle Salomé Ureña #29, San Francisco de Macorís',
    birthDate: '1980-04-21',
    email: 'alejandro.terrero08@gmail.com',
    phoneNumber: '+18295551234',
    province: 'Santo Domingo',
    city: 'Santo Domingo Oeste',

    ocupation: 'Bombero',
    gender: 'M',
    shirtSize: 'XL',

    memberDivision: 'Pioneros',
    destId: 'dest-08',
    sectionalId: 'sec-este-02',
    regionalId: 'reg-este',
    status: 'active',
  },
  {
    id: 'member-09',
    fullName: 'Luis Miguel Santana',
    memberAddress: 'Calle Imbert #15, Moca, Espaillat',
    birthDate: '1995-12-05',
    email: 'luis.santana09@hotmail.com',
    phoneNumber: '+18495554321',
    province: 'Santiago',
    city: 'Santiago',
    memberDivision: 'Liderazgo',
    destId: 'dest-09',
    sectionalId: 'sec-central-05',
    regionalId: 'reg-central',
    status: 'active',
  },
  {
    id: 'member-10',
    fullName: 'Shawn De la Cruz',
    memberAddress: 'Av. Enriquillo #60, Barahona',
    birthDate: '2008-07-18',
    email: 'shawn.delacruz10@gmail.com',
    phoneNumber: '+18095556781',
    province: 'Distrito Nacional',
    city: 'Distrito Nacional',
    memberDivision: 'Exploradores',
    destId: 'dest-10',
    sectionalId: 'sec-central-05',
    regionalId: 'reg-central',
    status: 'active',
  },

  // -------- NORTE --------
  {
    id: 'member-11',
    fullName: 'Soren Durán',
    memberAddress: 'Calle Sánchez #77, Azua',
    birthDate: '2004-02-11',
    email: 'soren.duran11@yahoo.com',
    phoneNumber: '+18295552468',
    province: 'Puerto Plata',
    city: 'Puerto Plata',
    memberDivision: 'Navegantes',
    destId: 'dest-15',
    sectionalId: 'sec-norte-01',
    regionalId: 'reg-norte',
    status: 'active',
  },
  {
    id: 'member-12',

    fullName: 'José Antonio Pérez',
    avatarUrl: '/assets/images/avatars/members/member-12.jpg',
    memberAddress: 'Calle Principal #7, Higüey, La Altagracia',
    birthDate: '2000-05-25',
    email: 'jose.perez01@gmail.com',
    phoneNumber: '+18095550143',
    province: 'Santo Domingo',
    city: 'Santo Domingo Este',

    memberDivision: 'Liderazgo',

    destId: 'dest-12',
    sectionalId: 'sec-este-01',
    regionalId: 'reg-este',

    status: 'active',
  },
  {
    id: 'member-13',
    fullName: 'Brycen Jiménez',
    memberAddress: 'Calle Independencia #9, San Juan de la Maguana',
    birthDate: '2002-01-27',
    email: 'brycen.jimenez13@hotmail.com',
    phoneNumber: '+18095559876',
    province: 'La Vega',
    city: 'La Vega',
    memberDivision: 'Liderazgo',
    destId: 'dest-17',
    sectionalId: 'sec-norte-01',
    regionalId: 'reg-norte',
    status: 'active',
  },
  {
    id: 'member-14',
    fullName: 'Giana Batista',
    memberAddress: 'Av. Francisco Domínguez Charro #101, San Pedro de Macorís',
    birthDate: '2009-06-15',
    email: 'giana.batista14@gmail.com',
    phoneNumber: '+18295556543',
    province: 'Duarte',
    city: 'San Francisco de Macorís',
    memberDivision: 'Exploradores',
    destId: 'dest-17',
    sectionalId: 'sec-norte-01',
    regionalId: 'reg-norte',
    status: 'active',
  },
  {
    id: 'member-15',
    fullName: 'Aspen Reyes',
    memberAddress: 'Av. Francisco Domínguez Charro #101, San Pedro de Macorís',
    birthDate: '2006-09-03',
    email: 'aspen.reyes15@yahoo.com',
    phoneNumber: '+18495553210',
    province: 'Espaillat',
    city: 'Moca',
    memberDivision: 'Pioneros',
    destId: 'dest-17',
    sectionalId: 'sec-norte-01',
    regionalId: 'reg-norte',
    status: 'active',
  },

  // -------- SUR --------
  {
    id: 'member-16',
    fullName: 'Colten Aguilar',
    memberAddress: 'Av. Francisco Domínguez Charro #101, San Pedro de Macorís',
    birthDate: '2005-03-22',
    email: 'colten.aguilar16@gmail.com',
    phoneNumber: '+18095551122',
    province: 'Barahona',
    city: 'Barahona',
    memberDivision: 'Pioneros',
    destId: 'dest-20',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
  {
    id: 'member-17',
    fullName: 'Angélica Morales',
    memberAddress: 'Calle Duarte #45, Ensanche Ozama, Santo Domingo Este',
    birthDate: '1949-08-01',
    email: 'angelica.morles17@hotmail.com',
    phoneNumber: '+18295553244',
    province: 'Azua',
    city: 'Azua1',
    memberDivision: 'Seguidores',
    destId: 'dest-21',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
  {
    id: 'member-33',
    fullName: 'Pedro Morales',
    memberAddress: 'Calle Duarte #45, Ensanche Ozama, Santo Domingo Este',
    birthDate: '1999-08-01',
    email: 'pedro.morles17@hotmail.com',
    phoneNumber: '+18295473244',
    province: 'Azua',
    city: 'Azua1',
    memberDivision: 'Seguidores',
    destId: 'dest-21',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
  {
    id: 'member-18',
    fullName: 'Selina Núñez',
    memberAddress: 'Av. Independencia #88, Distrito Nacional',
    birthDate: '2008-12-19',
    email: 'selina.nunez18@gmail.com',
    phoneNumber: '+18495555566',
    province: 'Peravia',
    city: 'Baní',
    memberDivision: 'Exploradores',
    destId: 'dest-21',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
  {
    id: 'member-19',
    fullName: 'Lawson Báez',
    memberAddress: 'Calle Restauración #12, Santiago',
    birthDate: '2004-05-07',
    email: 'lawson.baez19@yahoo.com',
    phoneNumber: '+18095557788',
    province: 'San Juan',
    city: 'San Juan de la Maguana',
    memberDivision: 'Navegantes',
    destId: 'dest-21',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
  {
    id: 'member-20',
    fullName: 'Ariana Peña',
    memberAddress: 'Av. Pedro A. Rivera #34, La Vega',
    birthDate: '2011-02-14',
    email: 'ariana.pena20@gmail.com',
    phoneNumber: '+18295559900',
    province: 'San Pedro de Macorís',
    city: 'San Pedro de Macorís',
    memberDivision: 'Exploradores',
    destId: 'dest-21',
    sectionalId: 'sec-sur-01',
    regionalId: 'reg-sur',
    status: 'active',
  },
];

/* ----------------------- MEMBERS UP-----------------------*/

/* ----------------------- REGIONALS DOWN-----------------------*/
export const REGIONALS = [
  {
    id: 'reg-central',
    name: 'Región Central',
    avatarUrl: '/assets/images/avatars/regionals/reg-central.jpg',
    email: 'regioncentral01@gmail.com'
  },
  { id: 'reg-norte', name: 'Región Norte', email: 'regionnorte02@gmail.com' },
  { id: 'reg-sur', name: 'Región Sur', email: 'regionsur03@gmail.com' },
  { id: 'reg-este', name: 'Región Este', email: 'regioneste04@gmail.com' },
];


/* ----------------------- SECTIONALS DOWN-----------------------*/
export const SECTIONALS = [
  // ESTE
  {
    id: 'sec-este-01',
    name: 'Tiburones del Este',
    avatarUrl: '/assets/images/avatars/sectionals/sec-este-01.jpg',
    regionalId: 'reg-central',
    email: 'tiburones.este@email.com',
  },
  {
    id: 'sec-este-02',
    name: 'Guerreros del Este',
    regionalId: 'reg-este',
    email: 'guerreros.este@email.com',
  },
  {
    id: 'sec-este-03',
    name: 'Leones del Este',
    regionalId: 'reg-este',
    email: 'leones.este@email.com',
  },
  {
    id: 'sec-este-04',
    name: 'Águilas del Este',
    regionalId: 'reg-este',
    email: 'aguilas.este@email.com',
  },
  {
    id: 'sec-este-05',
    name: 'Halcones del Este',
    regionalId: 'reg-este',
    email: 'halcones.este@email.com',
  },

  // CENTRAL
  {
    id: 'sec-central-01',
    name: 'Sección Central 1',
    regionalId: 'reg-central',
    email: 'central1@email.com',
  },
  {
    id: 'sec-central-02',
    name: 'Sección Central 2',
    regionalId: 'reg-central',
    email: 'central2@email.com',
  },
  {
    id: 'sec-central-03',
    name: 'Sección Central 3',
    regionalId: 'reg-central',
    email: 'central3@email.com',
  },
  {
    id: 'sec-central-04',
    name: 'Sección Central 4',
    regionalId: 'reg-central',
    email: 'central4@email.com',
  },
  {
    id: 'sec-central-05',
    name: 'Sección Central 5',
    regionalId: 'reg-central',
    email: 'central5@email.com',
  },

  // NORTE
  {
    id: 'sec-norte-01',
    name: 'Leones del Norte',
    regionalId: 'reg-norte',
    email: 'leones.norte@email.com',
  },
  {
    id: 'sec-norte-02',
    name: 'Osos del Norte',
    regionalId: 'reg-norte',
    email: 'osos.norte@email.com',
  },
  {
    id: 'sec-norte-03',
    name: 'Lobos del Norte',
    regionalId: 'reg-norte',
    email: 'lobos.norte@email.com',
  },
  {
    id: 'sec-norte-04',
    name: 'Halcones del Norte',
    regionalId: 'reg-norte',
    email: 'halcones.norte@email.com',
  },
  {
    id: 'sec-norte-05',
    name: 'Pumas del Norte',
    regionalId: 'reg-norte',
    email: 'pumas.norte@email.com',
  },

  // SUR
  {
    id: 'sec-sur-01',
    name: 'Águilas del Sur',
    regionalId: 'reg-sur',
    email: 'aguilas.sur@email.com',
  },
  {
    id: 'sec-sur-02',
    name: 'Tigres del Sur',
    regionalId: 'reg-sur',
    email: 'tigres.sur@email.com',
  },
  {
    id: 'sec-sur-03',
    name: 'Panteras del Sur',
    regionalId: 'reg-sur',
    email: 'panteras.sur@email.com',
  },
  {
    id: 'sec-sur-04',
    name: 'Cóndores del Sur',
    regionalId: 'reg-sur',
    email: 'condores.sur@email.com',
  },
  {
    id: 'sec-sur-05',
    name: 'Toros del Sur',
    regionalId: 'reg-sur',
    email: 'toros.sur@email.com',
  },
];

// export const _sectionalNames = [
//   'Tiburones del Este',
//   'Tiburones del Este',
//   'Tiburones del Este',
//   'Tiburones del Este',
//   'Sección 5',
//   'Sección 6',
//   'Sección 7',
//   'Sección 8',
//   'Sección 9',
//   'Sección 10',
//   'Sección 11',
//   'Sección 12',
//   'Sección 13',
//   'Sección 14',
//   'Sección 15',
//   'Sección 16',
//   'Sección 17',
//   'Sección 18',
//   'Sección 19',
//   'Sección 20',
//   'Sección 21',
//   'Sección 22',
//   'Sección 23',
//   'Sección 24',
// ];

// export const _sectionalEmails = [
//   'tiburones.este@email.com',
//   'seccion2@email.com',
//   'seccion3@email.com',
//   'seccion4@email.com',
//   'seccion5@email.com',
//   'seccion6@email.com',
//   'seccion7@email.com',
//   'seccion8@email.com',
//   'seccion9@email.com',
//   'seccion10@email.com',
//   'seccion11@email.com',
//   'seccion12@email.com',
//   'seccion13@email.com',
//   'seccion14@email.com',
//   'seccion15@email.com',
//   'seccion16@email.com',
//   'seccion17@email.com',
//   'seccion18@email.com',
//   'seccion19@email.com',
//   'seccion20@email.com',
//   'seccion21@email.com',
//   'seccion22@email.com',
//   'seccion23@email.com',
//   'seccion24@email.com',
// ];
/* ----------------------- SECTIONALS UP-----------------------*/

/* ----------------------- DEST DOWN-----------------------*/
export const DESTS = [
  // ESTE actualizado
  {
    id: 'dest-018',
    name: 'Destacamento 18',
    avatarUrl: '/assets/images/avatars/dests/dest-01.jpg',
    churchId: 'iglesia-aposento-alto',
    churchAddress: 'Calle Masonería #86, Santo Domingo Este',
    sectionalId: 'sec-este-01',
    membershipStatus: 'registered',

    destMeetingTimes: 'Domingos 10:00 A.M. a 11:30 A.M.',
    shepardName: 'Margarita Guillén Rodríguez',
    churchPhone: '18097878833',
    destProvince: 'Santo Domingo',
  },
  {
    id: 'dest-02',
    name: 'Destacamento 2',
    churchId: 'iglesia-el-calvario',
    churchAddress: 'Calle San Vicente de Paúl #128, Alma Rosa I, Santo Domingo Este',
    sectionalId: 'sec-este-01',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-03',
    name: 'Destacamento 3',
    churchId: 'iglesia-fuente-de-vida',
    churchAddress: 'Avenida Charles de Gaulle Km 9½, Villa Carmen, Santo Domingo Este',
    sectionalId: 'sec-este-02',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-04',
    name: 'Destacamento 4',
    churchId: 'iglesia-bethel',
    churchAddress: 'Calle Juan Pablo Duarte #67, Sector Invivienda, Santo Domingo Este',
    sectionalId: 'sec-este-02',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-05',
    name: 'Destacamento 5',
    churchId: 'iglesia-monte-de-sion',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-este-01',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-06',
    name: 'Destacamento 6',
    churchId: 'iglesia-getsemani',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-este-01',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-07',
    name: 'Destacamento 7',
    churchId: 'iglesia-vida-nueva',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-este-02',
    membershipStatus: 'registered',

  },
  {
    id: 'dest-08',
    name: 'Destacamento 8',
    churchId: 'iglesia-shalom',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-este-02',
  },

  // CENTRAL
  {
    id: 'dest-09',
    name: 'Destacamento 9',
    churchId: 'iglesia-la-alabanza',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-central-05',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-10',
    name: 'Destacamento 10',
    churchId: 'iglesia-redencion',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-central-05',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-12',
    name: 'Destacamento 12',
    churchId: 'iglesia-redencion',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-central-05',
    membershipStatus: 'registered',
  },

  // NORTE
  {
    id: 'dest-15',
    name: 'Destacamento 15',
    churchId: 'iglesia-jerusalen',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-norte-01',
    membershipStatus: 'registered',

  },
  {
    id: 'dest-17',
    name: 'Destacamento 17',
    churchId: 'iglesia-principe-de-paz',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-norte-01',
    membershipStatus: 'registered',

  },

  // SUR
  {
    id: 'dest-20',
    name: 'Destacamento 20',
    churchId: 'iglesia-emanuel',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-sur-01',
    membershipStatus: 'registered',
  },
  {
    id: 'dest-21',
    name: 'Destacamento 21',
    churchId: 'iglesia-nueva-esperanza',
    churchAddress: 'Avenida Hípica #22, Urbanización Tropical, Santo Domingo Este',
    sectionalId: 'sec-sur-01',
    membershipStatus: 'registered',
  },
];

export const CHURCHES = [
  { id: 'iglesia-aposento-alto', name: 'Iglesia Aposento Alto' },
  { id: 'iglesia-el-calvario', name: 'Iglesia El Calvario' },
  { id: 'iglesia-fuente-de-vida', name: 'Iglesia Fuente de Vida' },
  { id: 'iglesia-bethel', name: 'Iglesia Bethel' },
  { id: 'iglesia-monte-de-sion', name: 'Iglesia Monte de Sión' },
  { id: 'iglesia-getsemani', name: 'Iglesia Getsemaní' },
  { id: 'iglesia-vida-nueva', name: 'Iglesia Vida Nueva' },
  { id: 'iglesia-shalom', name: 'Iglesia Shalom' },
  { id: 'iglesia-la-alabanza', name: 'Iglesia La Alabanza' },
  { id: 'iglesia-redencion', name: 'Iglesia Redención' },
  { id: 'iglesia-manantial-de-vida', name: 'Iglesia Manantial de Vida' },
  { id: 'iglesia-cristo-vive', name: 'Iglesia Cristo Vive' },
  { id: 'iglesia-luz-del-mundo', name: 'Iglesia Luz del Mundo' },
  { id: 'iglesia-el-buen-pastor', name: 'Iglesia El Buen Pastor' },
  { id: 'iglesia-jerusalen', name: 'Iglesia Jerusalén' },
  { id: 'iglesia-casa-de-dios', name: 'Iglesia Casa de Dios' },
  { id: 'iglesia-alfa-y-omega', name: 'Iglesia Alfa y Omega' },
  { id: 'iglesia-roca-eterna', name: 'Iglesia Roca Eterna' },
  { id: 'iglesia-emanuel', name: 'Iglesia Emanuel' },
  { id: 'iglesia-principe-de-paz', name: 'Iglesia Príncipe de Paz' },
  { id: 'iglesia-nueva-esperanza', name: 'Iglesia Nueva Esperanza' },
  { id: 'iglesia-fe-y-salvacion', name: 'Iglesia Fe y Salvación' },
  { id: 'iglesia-el-shaddai', name: 'Iglesia El Shaddai' },
  { id: 'iglesia-tabernaculo-de-gloria', name: 'Iglesia Tabernáculo de Gloria' },
];


export const _destMemberCounts = [
  'Cantidad: 8',
  'Cantidad: 15',
  'Cantidad: 23',
  'Cantidad: 12',
  'Cantidad: 30',
  'Cantidad: 18',
  'Cantidad: 25',
  'Cantidad: 10',
  'Cantidad: 40',
  'Cantidad: 16',
  'Cantidad: 22',
  'Cantidad: 35',
  'Cantidad: 14',
  'Cantidad: 28',
  'Cantidad: 19',
  'Cantidad: 9',
  'Cantidad: 33',
  'Cantidad: 27',
  'Cantidad: 11',
  'Cantidad: 20',
  'Cantidad: 38',
  'Cantidad: 17',
  'Cantidad: 24',
  'Cantidad: 31',
];

/* ----------------------- DEST UP-----------------------*/

export const _memberFullNames = [
  'José Antonio Pérez',
  'Carlos Alberto Rodríguez',
  'María Fernanda Martínez',
  'Pedro Julio Sepúlveda',
  'Rafael Jiménez',
  'Laura Sofía Hernández',
  'Cristopher Cárdenas',
  'Melanie Núñez',
  'Luis Miguel Santana',
  'Shawn De la Cruz',
  'Soren Durán',
  'Cortez Herrera',
  'Brycen Jiménez',
  'Giana Batista',
  'Aspen Reyes',
  'Colten Aguilar',
  'Angélica Morales',
  'Selina Núñez',
  'Lawson Báez',
  'Ariana Peña',
  'Amiah García',
  'Harold Sánchez',
  'Esperanza Martínez',
  'Mireya Concepción',
  'Roberto Valdez',
  'Karla Ortiz',
  'Andrés Ramos',
  'Yessica Mendoza',
  'Miguel Batista',
  'Paola Reyes',
  'Héctor Medina',
  'Gloria Fermín',
  'Felipe Torres',
  'Nancy Lora',
  'Óscar Paredes',
  'Daniel Castillo',
  'Sofía Peralta',
  'Kevin Ramírez',
  'Patricia Guillén',
  'Jonathan Mejía',
];

export const _destMemberships = [
  'Registrado',
  'No registrado',
  'Registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'No registrado',
  'Registrado',
  'No registrado',
];


export const _firstNames = [
  `Mossie`,
  `David`,
  `Ebba`,
  `Chester`,
  `Eula`,
  `Jaren`,
  `Boyd`,
  `Brady`,
  `Aida`,
  `Anastasia`,
  `Gregoria`,
  `Julianne`,
  `Ila`,
  `Elyssa`,
  `Lucio`,
  `Lewis`,
  `Jacinthe`,
  `Molly`,
  `Brown`,
  `Fritz`,
  `Keon`,
  `Ella`,
  `Ken`,
  `Whitney`,
];

export const _lastNames = [
  `Carroll`,
  `Simonis`,
  `Yost`,
  `Hand`,
  `Emmerich`,
  `Wilderman`,
  `Howell`,
  `Sporer`,
  `Boehm`,
  `Morar`,
  `Koch`,
  `Reynolds`,
  `Padberg`,
  `Watsica`,
  `Upton`,
  `Yundt`,
  `Pfeffer`,
  `Parker`,
  `Zulauf`,
  `Treutel`,
  `McDermott`,
  `McDermott`,
  `Cruickshank`,
  `Parisian`,
];

// ----------------------------------------------------------------------

export const _phoneNumbers = [
  /*Los números de teléfonos deben mantener ese formato (+18095550143)
  para que en aplicación se visualicen como (809) 555-9876.*/
  '+18095550143',
  '+18295550198',
  '+18495550958',
  '+18095555432',
  '+18295555678',
  '+18495553456',
  '+18095556789',
  '+18295551234',
  '+18495554321',
  '+18095556781',
  '+18295552468',
  '+18495551357',
  '+18095559876',
  '+18295556543',
  '+18495553210',
  '+18095551122',
  '+18295553344',
  '+18495555566',
  '+18095557788',
  '+18295559900',
  '+18495552211',
  '+18095554433',
  '+18295556655',
  '+18495558877',
  '+18095551010',
  '+18295552020',
  '+18495553030',
  '+18095554040',
  '+18295555050',
  '+18495556060',
  '+18095557070',
  '+18295558080',
  '+18495559090',
  '+18095551111',
  '+18295552222',
  '+18495553333',
  '+18095554444',
  '+18295556666',
  '+18495557777',
  '+18095558888',
];


// ----------------------------------------------------------------------

export const _countryNames = [
  'United States',
  'República Dominicana',
  'United Kingdom',
  'Australia',
  'India',
  'Germany',
  'France',
  'Japan',
  'China',
  'Brazil',
  'South Africa',
  'Russia',
  'Mexico',
  'Italy',
  'Spain',
  'Netherlands',
  'Sweden',
  'Switzerland',
  'South Korea',
  'Argentina',
  'New Zealand',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'Turkey',
  'Saudi Arabia',
  'United Arab Emirates',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Israel',
  'Greece',
  'Ireland',
  'Portugal',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
];

// ----------------------------------------------------------------------

export const _roles = [
  `CEO`,
  `CTO`,
  `Project Coordinator`,
  `Team Leader`,
  `Software Developer`,
  `Marketing Strategist`,
  `Data Analyst`,
  `Product Owner`,
  `Graphic Designer`,
  `Operations Manager`,
  `Customer Support Specialist`,
  `Sales Manager`,
  `HR Recruiter`,
  `Business Consultant`,
  `Financial Planner`,
  `Network Engineer`,
  `Content Creator`,
  `Quality Assurance Tester`,
  `Public Relations Officer`,
  `IT Administrator`,
  `Compliance Officer`,
  `Event Planner`,
  `Legal Counsel`,
  `Training Coordinator`,
];

export const _sectionalXDestMemberCounts = [
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
];

export const _nationalEstructures = [
  'Consejo Nacional',
  'Consejo Ejecutivo',
];

export const _nationalXAssignedRegionals = [
  'Región Central',
  'Región Norte',
  'Región Sur',
  'Región Este',

];

export const _regionalXSectionalMemberCounts = [
  `Cantidad: 94`,
  `Cantidad: 92`,
  `Cantidad: 75`,
  `Cantidad: 84`,
];

export const _regionalXSectionalXDestCounts = [
  `Cantidad: 29`,
  `Cantidad: 18`,
  `Cantidad: 12`,
  `Cantidad: 21`,
];


// export const _memberPositionsFilter = [
//   'Coordinador Dest.',
//   'Coordinador As. Dest.',
//   'Pastor',
//   'Líder de patrulla',
//   'Guía auxiliar',
//   'Escriba',
//   'Guía de patrulla',
// ]; //////


export const _memberPositions = [
  'Coordinador Dest.',
  'Coordinador As. Dest.',
  'Pastor',
  'Guía de patrulla',
  'Líder de patrulla',
  'Guía auxiliar',
  'Escriba',
  'Guía de patrulla',
  'Líder de patrulla',
  'Guía auxiliar',
  'Escriba',
  'Pastor',
  'Guía de patrulla',
  'Líder de patrulla',
  'Guía auxiliar',
  'Escriba',
  'Pastor',
  'Guía de patrulla',
  'Líder de patrulla',
  'Guía auxiliar',
  'Escriba',
  'Pastor',
  'Líder de patrulla',
];

// ----------------------------------------------------------------------

export const _postTitles = [
  `The Future of Renewable Energy: Innovations and Challenges Ahead`,
  `Exploring the Impact of Artificial Intelligence on Modern Healthcare`,
  `Climate Change and Its Effects on Global Food Security`,
  `The Rise of Remote Work: Benefits, Challenges, and Future Trends`,
  `Understanding Blockchain Technology: Beyond Cryptocurrency`,
  `Mental Health in the Digital Age: Navigating Social Media and Well-being`,
  `Sustainable Fashion: How the Industry is Going Green`,
  `Space Exploration: New Frontiers and the Quest for Extraterrestrial Life`,
  `The Evolution of E-Commerce: Trends Shaping the Online Retail Landscape`,
  `Cybersecurity in the 21st Century: Protecting Data in a Digital World`,
  `The Role of Big Data in Transforming Business Strategies`,
  `Genetic Engineering: Ethical Considerations and Future Prospects`,
  `Urban Farming: A Solution to Food Deserts and Urban Sustainability`,
  `The Psychology of Consumer Behavior: What Drives Our Purchasing Decisions?`,
  `Renewable Energy vs. Fossil Fuels: Which is the Future?`,
  `Artificial Intelligence in Education: Enhancing Learning Experiences`,
  `The Impact of Climate Change on Global Migration Patterns`,
  `5G Technology: Revolutionizing Connectivity and Communication`,
  `The Gig Economy: Opportunities, Risks, and the Future of Work`,
  `Smart Cities: Integrating Technology for Sustainable Urban Living`,
  `The Influence of Pop Culture on Modern Society`,
  `Innovations in Medicine: From Telehealth to Personalized Treatment`,
  `The Environmental Cost of Fast Fashion: What Can Consumers Do?`,
  `The Intersection of Art and Technology: Digital Art in the 21st Century`,
];

// ----------------------------------------------------------------------

export const _productNames = [
  `Urban Explorer Sneakers`,
  `Classic Leather Loafers`,
  `Mountain Trekking Boots`,
  `Elegance Stiletto Heels`,
  `Comfy Running Shoes`,
  `Chic Ballet Flats`,
  `Vintage Oxford Shoes`,
  `Waterproof Hiking Boots`,
  `Casual Slip-On Sneakers`,
  `Premium Dress Shoes`,
  `Sporty Trail Runners`,
  `Sophisticated Brogues`,
  `Beach Sandals`,
  `Stylish Wedge Heels`,
  `Lightweight Training Shoes`,
  `Luxurious Moccasins`,
  `Durable Work Boots`,
  `Trendy Platform Sneakers`,
  `Cozy Winter Boots`,
  `Fashion Ankle Boots`,
  `Breathable Tennis Shoes`,
  `Elegant Evening Pumps`,
  `Modern Skate Shoes`,
  `Comfortable Walking Shoes`,
];

// ----------------------------------------------------------------------

export const _tourNames = [
  `Majestic Mountain Adventures`,
  `Island Hopping Extravaganza`,
  `Cultural Wonders of Europe`,
  `Safari Expedition in Africa`,
  `Grand Canyon Explorer`,
  `Historic Cities of Asia`,
  `Tropical Paradise Getaway`,
  `Alaskan Wilderness Tour`,
  `Mediterranean Cruise Voyage`,
  `Enchanting Eastern Europe`,
  `Scenic Coastal Road Trip`,
  `Ancient Ruins Discovery`,
  `Australian Outback Adventure`,
  `Northern Lights Experience`,
  `Wildlife Wonders of South America`,
  `Royal Castles and Palaces`,
  `Ultimate Beach Retreat`,
  `National Parks Exploration`,
  `Gastronomic Tour of Italy`,
  `Hiking Trails of New Zealand`,
  `Art and History of France`,
  `Exotic Temples of India`,
  `Canadian Rockies Journey`,
  `Caribbean Sun and Fun`,
];

// ----------------------------------------------------------------------

export const _jobTitles = [
  `Software Engineer`,
  `Marketing Manager`,
  `Data Scientist`,
  `Graphic Designer`,
  `Financial Analyst`,
  `Human Resources Specialist`,
  `Project Manager`,
  `Sales Executive`,
  `Content Writer`,
  `Network Administrator`,
  `Customer Service Representative`,
  `Product Manager`,
  `Business Analyst`,
  `Mechanical Engineer`,
  `Operations Manager`,
  `UX/UI Designer`,
  `Accountant`,
  `Social Media Manager`,
  `Research Scientist`,
  `Legal Advisor`,
  `Public Relations Specialist`,
  `Health and Safety Officer`,
  `IT Support Specialist`,
  `Environmental Consultant`,
];

// ----------------------------------------------------------------------

export const _companyNames = [
  `Lueilwitz and Sons`,
  `Gleichner, Mueller and Tromp`,
  `Nikolaus - Leuschke`,
  `Hegmann, Kreiger and Bayer`,
  `Grimes Inc`,
  `Durgan - Murazik`,
  `Altenwerth, Medhurst and Roberts`,
  `Raynor Group`,
  `Mraz, Donnelly and Collins`,
  `Padberg - Bailey`,
  `Heidenreich, Stokes and Parker`,
  `Pagac and Sons`,
  `Rempel, Hand and Herzog`,
  `Dare - Treutel`,
  `Kihn, Marquardt and Crist`,
  `Nolan - Kunde`,
  `Wuckert Inc`,
  `Dibbert Inc`,
  `Goyette and Sons`,
  `Feest Group`,
  `Bosco and Sons`,
  `Bartell - Kovacek`,
  `Schimmel - Raynor`,
  `Tremblay LLC`,
];

export const _sectionalDestCounts = [
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
];

export const _nationalXMemberPositions = [
  `Dir. Min. Infantiles`,
  `Dir. Nacional`,
  `Cap. Nacional`,
  `Subdir. Nacional`,
  `Coord. Nal. Adiestramiento`,
  `Coord. Nal. Promoción`,
  `Coord. Nal. Producción`,
  `Coord. Nal. Programa`,
  `Pres. Consejo Nal.`,
  `Dirs. Regionales`,
  `Tesorero Ejec.`,
  `Secretario Ejec.`,
  `Dir. Min. Infantiles`,
  `Dir. Nacional`,
  `Cap. Nacional`,
  `Subdir. Nacional`,
  `Coord. Nal. Adiestramiento`,
  `Coord. Nal. Promoción`,
  `Coord. Nal. Producción`,
  `Coord. Nal. Programa`,
  `Pres. Consejo Nal.`,
  `Dirs. Regionales`,
  `Tesorero Ejec.`,
  `Secretario Ejec.`,
];

export const _regionalXSectionalCounts = [
  `Cantidad: 12`,
  `Cantidad: 22`,
  `Cantidad: 9`,
  `Cantidad: 15`,
];

export const _memberDivisionNames = [
  'Liderazgo',
  'Exploradores',
  'Pioneros',
  'Navegantes',
  'Exploradores',
  'Seguidores',
  'Pioneros',
  'Navegantes',
  'Exploradores',
  'Seguidores',
  'Pioneros',
  'Navegantes',
  'Exploradores',
  'Seguidores',
  'Pioneros',
  'Navegantes',
  'Exploradores',
  'Seguidores',
  'Pioneros',
  'Navegantes',
  'Exploradores',
  'Seguidores',
  'Pioneros',
  'Navegantes',
];
// ----------------------------------------------------------------------

export const _tags = [
  `Technology`,
  `Health and Wellness`,
  `Travel`,
  `Finance`,
  `Education`,
  `Food and Beverage`,
  `Fashion`,
  `Home and Garden`,
  `Sports`,
  `Entertainment`,
  `Business`,
  `Science`,
  `Automotive`,
  `Beauty`,
  `Fitness`,
  `Lifestyle`,
  `Real Estate`,
  `Parenting`,
  `Pet Care`,
  `Environmental`,
  `DIY and Crafts`,
  `Gaming`,
  `Photography`,
  `Music`,
];

// ----------------------------------------------------------------------

export const _taskNames = [
  `Prepare Monthly Financial Report`,
  `Design New Marketing Campaign`,
  `Analyze Customer Feedback`,
  `Update Website Content`,
  `Conduct Market Research`,
  `Develop Software Application`,
  `Organize Team Meeting`,
  `Create Social Media Posts`,
  `Review Project Plan`,
  `Implement Security Protocols`,
  `Write Technical Documentation`,
  `Test New Product Features`,
  `Manage Client Inquiries`,
  `Train New Employees`,
  `Coordinate Logistics`,
  `Monitor Network Performance`,
  `Develop Training Materials`,
  `Draft Press Release`,
  `Prepare Budget Proposal`,
  `Evaluate Vendor Proposals`,
  `Perform Data Analysis`,
  `Conduct Quality Assurance`,
  `Plan Event Logistics`,
  `Optimize SEO Strategies`,
];

// ----------------------------------------------------------------------

export const _courseNames = [
  `Introduction to Python Programming`,
  `Digital Marketing Fundamentals`,
  `Data Science with R`,
  `Graphic Design Essentials`,
  `Financial Planning for Beginners`,
  `Human Resource Management Basics`,
  `Project Management Fundamentals`,
  `Sales Techniques and Strategies`,
  `Content Writing Mastery`,
  `Network Security Fundamentals`,
  `Customer Service Excellence`,
  `Product Management Essentials`,
  `Business Analytics with Excel`,
  `Mechanical Engineering Principles`,
  `Leadership and Team Management`,
  `User Experience (UX) Design Basics`,
  `Accounting Fundamentals`,
  `Social Media Marketing Mastery`,
  `Biotechnology Essentials`,
  `Legal Studies for Non-Lawyers`,
  `Public Speaking Confidence`,
  `Health and Wellness Coaching`,
  `Web Development Bootcamp`,
  `Photography Masterclass`,
];

// ----------------------------------------------------------------------

export const _fileNames = [
  'cover-2.jpg',
  'design-suriname-2015.mp3',
  'expertise-2015-conakry-sao-tome-and-principe-gender.mp4',
  'money-popup-crack.pdf',
  'cover-4.jpg',
  'cover-6.jpg',
  'large-news.txt',
  'nauru-6015-small-fighter-left-gender.psd',
  'tv-xs.doc',
  'gustavia-entertainment-productivity.docx',
  'vintage-bahrain-saipan.xls',
  'indonesia-quito-nancy-grace-left-glad.xlsx',
  'legislation-grain.zip',
  'large-energy-dry-philippines.rar',
  'footer-243-ecuador.iso',
  'kyrgyzstan-04795009-picabo-street-guide-style.ai',
  'india-data-large-gk-chesterton-mother.eps',
  'footer-barbados-celine-dion.ppt',
  'socio-respectively-366996.pptx',
  'socio-ahead-531437-sweden-popup.wav',
  'trinidad-samuel-morse-bring.m4v',
  'cover-12.jpg',
  'cover-18.jpg',
  'xl-david-blaine-component-tanzania-books.pdf',
];

export const _eventNames = [
  `Annual General Meeting`,
  `Summer Music Festival`,
  `Tech Innovators Conference`,
  `Charity Gala Dinner`,
  `Spring Art Exhibition`,
  `Corporate Training Workshop`,
  `Community Health Fair`,
  `Startup Pitch Night`,
  `Regional Sports Tournament`,
  `Book Launch Event`,
  `Film Premiere Screening`,
  `Industry Networking Mixer`,
  `Holiday Craft Fair`,
  `Environmental Awareness Week`,
  `New Year's Eve Party`,
  `Product Release Showcase`,
  `Cultural Heritage Festival`,
  `Science and Technology Expo`,
  `Annual Awards Ceremony`,
  `Fashion Week Runway Show`,
  `Food and Wine Tasting`,
  `Outdoor Adventure Camp`,
  `Leadership Summit`,
  `Wedding Expo`,
];

// ----------------------------------------------------------------------

export const _sentences = [
  `The sun slowly set over the horizon, painting the sky in vibrant hues of orange and pink.`,
  `She eagerly opened the gift, her eyes sparkling with excitement.`,
  `The old oak tree stood tall and majestic, its branches swaying gently in the breeze.`,
  `The aroma of freshly brewed coffee filled the air, awakening my senses.`,
  `The children giggled with joy as they ran through the sprinklers on a hot summer day.`,
  `He carefully crafted a beautiful sculpture out of clay, his hands skillfully shaping the intricate details.`,
  `The concert was a mesmerizing experience, with the music filling the venue and the crowd cheering in delight.`,
  `The waves crashed against the shore, creating a soothing symphony of sound.`,
  `The scent of blooming flowers wafted through the garden, creating a fragrant paradise.`,
  `She gazed up at the night sky, marveling at the twinkling stars that dotted the darkness.`,
  `The professor delivered a captivating lecture, engaging the students with thought-provoking ideas.`,
  `The hiker trekked through the dense forest, guided by the soft glow of sunlight filtering through the trees.`,
  `The delicate butterfly gracefully fluttered from flower to flower, sipping nectar with its slender proboscis.`,
  `The aroma of freshly baked cookies filled the kitchen, tempting everyone with its irresistible scent.`,
  'The majestic waterfall cascaded down the rocks, creating a breathtaking display of nature`s power.',
  `The actor delivered a powerful performance, moving the audience to tears with his emotional portrayal.`,
  `The book transported me to a magical world, where imagination knew no bounds.`,
  `The scent of rain filled the air as dark clouds gathered overhead, promising a refreshing downpour.`,
  `The chef skillfully plated the dish, turning simple ingredients into a work of culinary art.`,
  `The newborn baby let out a tiny cry, announcing its arrival to the world.`,
  `The athlete sprinted across the finish line, arms raised in victory as the crowd erupted in applause.`,
  `The ancient ruins stood as a testament to a civilization long gone, their grandeur still awe-inspiring.`,
  `The artist dipped the brush into vibrant paint, bringing the canvas to life with bold strokes and vivid colors.`,
  `The laughter of children echoed through the playground, filling the atmosphere with pure joy.`,
];

// ----------------------------------------------------------------------

export const _descriptions = [
  `Occaecati est et illo quibusdam accusamus qui. Incidunt aut et molestiae ut facere aut. Est quidem iusto praesentium excepturi harum nihil tenetur facilis. Ut omnis voluptates nihil accusantium doloribus eaque debitis.`,
  `Atque eaque ducimus minima distinctio velit. Laborum et veniam officiis. Delectus ex saepe hic id laboriosam officia. Odit nostrum qui illum saepe debitis ullam. Laudantium beatae modi fugit ut. Dolores consequatur beatae nihil voluptates rem maiores.`,
  `Rerum eius velit dolores. Explicabo ad nemo quibusdam. Voluptatem eum suscipit et ipsum et consequatur aperiam quia. Rerum nulla sequi recusandae illum velit quia quas. Et error laborum maiores cupiditate occaecati.`,
  `Et non omnis qui. Qui sunt deserunt dolorem aut velit cumque adipisci aut enim. Nihil quis quisquam nesciunt dicta nobis ab aperiam dolorem repellat. Voluptates non blanditiis. Error et tenetur iste soluta cupiditate ratione perspiciatis et. Quibusdam aliquid nam sunt et quisquam non esse.`,
  `Nihil ea sunt facilis praesentium atque. Ab animi alias sequi molestias aut velit ea. Sed possimus eos. Et est aliquid est voluptatem.`,
  `Non rerum modi. Accusamus voluptatem odit nihil in. Quidem et iusto numquam veniam culpa aperiam odio aut enim. Quae vel dolores. Pariatur est culpa veritatis aut dolorem.`,
  `Est enim et sit non impedit aperiam cumque animi. Aut eius impedit saepe blanditiis. Totam molestias magnam minima fugiat.`,
  `Unde a inventore et. Sed esse ut. Atque ducimus quibusdam fuga quas id qui fuga.`,
  `Eaque natus adipisci soluta nostrum dolorem. Nesciunt ipsum molestias ut aliquid natus ut omnis qui fugiat. Dolor et rem. Ut neque voluptatem blanditiis quasi ullam deleniti.`,
  `Nam et error exercitationem qui voluptate optio. Officia omnis qui accusantium ipsam qui. Quia sequi nulla perspiciatis optio vero omnis maxime omnis ipsum. Perspiciatis consequuntur asperiores veniam dolores.`,
  `Perspiciatis nulla ut ut ut voluptates totam consectetur eligendi qui. Optio ut cum. Dolorum sapiente qui laborum. Impedit temporibus totam delectus nihil. Voluptatem corrupti rem.`,
  `Distinctio omnis similique omnis eos. Repellat cumque rerum nisi. Reiciendis soluta non ut veniam temporibus. Accusantium et dolorem voluptas harum. Nemo eius voluptate dicta et hic nemo. Dolorem assumenda et beatae molestias sit quo mollitia quis consequatur.`,
  `Sed ut mollitia tempore ipsam et illum doloribus ut. Occaecati ratione veritatis explicabo. Omnis nam omnis sunt placeat tempore accusantium placeat distinctio velit.`,
  `Eum illo dicta et perspiciatis ut blanditiis eos sequi. Ea veritatis aut et voluptas aut. Laborum eos quia tempore a culpa.`,
  `Aut quos quae dolores repudiandae similique perferendis perferendis earum laudantium. Facere placeat natus nobis. Eius vitae ullam dolorem.`,
  `Vero dolorem et voluptatem fugit tempore a quam iure. Fuga consequatur corrupti sunt asperiores vitae. Libero totam repellendus animi debitis illum et sunt officia.`,
  `Cupiditate illum officiis id molestiae. Numquam non molestiae aliquid et natus sed hic. Alias quia explicabo sed corrupti sint. Natus in et odio qui unde facilis quia. Est sit eius laboriosam aliquid non aperiam quia quo corporis.`,
  `Et a ab. Optio aspernatur minus tempora amet vitae consectetur inventore cumque. Sed et omnis. Aspernatur a magnam.`,
  `Ipsum omnis et. Quia ea et autem tempore consequuntur veniam dolorem officiis. Ipsa dicta et ut quidem quia doloremque. Sequi vitae doloremque temporibus. Deserunt incidunt id aperiam itaque natus. Earum sit eaque quas incidunt nihil.`,
  `Quae consequatur reiciendis. Consequatur non optio. Eaque id placeat. Commodi quo officia aut repudiandae reiciendis tempore voluptatem et. Ut accusamus qui itaque maxime aliquam. Fugit ut animi molestiae porro maiores.`,
  `Modi hic asperiores ab cumque quam est aut. Voluptas atque quos molestias. Ut excepturi distinctio ipsam aspernatur sit.`,
  `Sunt totam facilis. Quam commodi voluptatem veniam. Tempora deleniti itaque fugit nihil voluptas.`,
  `Ipsam aliquam velit nobis repellendus officiis aut deserunt id et. Nihil sunt aut dolores aut. Dolores est ipsa quia et laborum quidem laborum accusamus id. Facilis odit quod hic laudantium saepe omnis nisi in sint. Sed cupiditate possimus id.`,
  `Magnam non eveniet optio optio ut aliquid atque. Velit libero aspernatur quis laborum consequatur laudantium. Tempora facere optio fugit accusantium ut. Omnis aspernatur reprehenderit autem esse ut ut enim voluptatibus.`,
];
