// ----------------------------------------------------------------------

export const LEADERSHIP_ASSIGNMENTS = [

    // 🔹 SIMULACIÓN 20 COORDINADORES DESTACAMENTO

    {
        id: 'lead-dest-018',
        memberId: 'member-01',
        level: 'dest',
        entityId: 'dest-018',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-01-asist',
        memberId: 'member-19',
        level: 'dest',
        entityId: 'dest-01',
        role: 'coordinador_asist_dest',
        // status: 'active', // no es necesario active
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-02',
        memberId: 'member-02',
        level: 'dest',
        entityId: 'dest-02',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-03',
        memberId: 'member-03',
        level: 'dest',
        entityId: 'dest-03',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },

    {
        id: 'lead-dest-05',
        memberId: 'member-17',
        level: 'dest',
        entityId: 'dest-05',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-06',
        memberId: 'member-06',
        level: 'dest',
        entityId: 'dest-06',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-07',
        memberId: 'member-07',
        level: 'dest',
        entityId: 'dest-07',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },

    {
        id: 'lead-dest-09',
        memberId: 'member-09',
        level: 'dest',
        entityId: 'dest-09',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-10',
        memberId: 'member-10',
        level: 'dest',
        entityId: 'dest-10',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-11',
        memberId: 'member-11',
        level: 'dest',
        entityId: 'dest-11',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-12',
        memberId: 'member-12',
        level: 'dest',
        entityId: 'dest-12',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-13',
        memberId: 'member-13',
        level: 'dest',
        entityId: 'dest-13',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-14',
        memberId: 'member-14',
        level: 'dest',
        entityId: 'dest-14',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-15',
        memberId: 'member-15',
        level: 'dest',
        entityId: 'dest-15',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-16',
        memberId: 'member-16',
        level: 'dest',
        entityId: 'dest-16',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-18',
        memberId: 'member-18',
        level: 'dest',
        entityId: 'dest-18',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-19',
        memberId: 'member-19',
        level: 'dest',
        entityId: 'dest-19',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-dest-20',
        memberId: 'member-20',
        level: 'dest',
        entityId: 'dest-20',
        role: 'coordinador_dest',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },

    // 🔹 SECCIONAL
    {
        id: 'lead-02a',
        memberId: 'member-04',
        level: 'sectional',
        entityId: 'sec-este-01',
        role: 'director_sectional',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-03',
        memberId: 'member-08',
        level: 'national',
        entityId: 'sec-este-02',
        role: 'director_nacional',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-04',
        memberId: 'member-01',
        level: 'sectional',
        entityId: 'sec-este-01',
        role: 'subdirector_sectional',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },


    // 🔹 REGIONALES
    {
        id: 'lead-reg-01',
        memberId: 'member-05',
        level: 'regional',
        entityId: 'reg-central',
        role: 'director_regional',
        status: 'active',
        startDate: null,
        endDate: null,
    },


    // 🔹 NATIONAL NACIONAL
    {
        id: 'lead-12a',
        memberId: 'member-12',
        level: 'national',
        entityId: 'national-root',
        role: 'coordinador_promocion_regional',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-11a',
        memberId: 'member-02',
        level: 'national',
        entityId: 'national-root',
        role: 'tesorero_ejecutivo',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    },
    {
        id: 'lead-13a',
        memberId: 'member-13',
        level: 'national',
        entityId: 'national-root',
        role: 'capellan_nacional',
        status: 'active',
        startDate: '2025-01-01',
        endDate: null,
    }

];